.TH "com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.ClassViewHolder" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.ClassViewHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 ViewHolder \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBClassViewHolder\fP (View view)"
.br
.ti -1c
.RI "void \fBbind\fP (\fBCourseCategoryItem\fP courseCourseCategoryItem)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final View \fBmView\fP"
.br
.ti -1c
.RI "final TextView \fBmTitle\fP"
.br
.ti -1c
.RI "final RecyclerView \fBmList\fP"
.br
.ti -1c
.RI "\fBCourseCategoryItem\fP \fBmItem\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 CourseRecyclerViewAdapter\&.java 第 89 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.ClassViewHolder\&.ClassViewHolder (View view)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 95 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.ClassViewHolder\&.bind (\fBCourseCategoryItem\fP courseCourseCategoryItem)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 102 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "\fBCourseCategoryItem\fP com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.ClassViewHolder\&.mItem"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 93 行定义\&.
.SS "final RecyclerView com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.ClassViewHolder\&.mList"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 92 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.ClassViewHolder\&.mTitle"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 91 行定义\&.
.SS "final View com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.ClassViewHolder\&.mView"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 90 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
