.TH "com.angelmsger.cslaboratory.login.Login.Response" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.login.Login.Response \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBResponse\fP ()"
.br
.ti -1c
.RI "\fBResponse\fP (int \fBcode\fP, \fBUser\fP \fBuser\fP)"
.br
.ti -1c
.RI "int \fBgetCode\fP ()"
.br
.ti -1c
.RI "void \fBsetCode\fP (int \fBcode\fP)"
.br
.ti -1c
.RI "\fBUser\fP \fBgetUser\fP ()"
.br
.ti -1c
.RI "void \fBsetUser\fP (\fBUser\fP \fBuser\fP)"
.br
.in -1c
.SS "静态 Public 属性"

.in +1c
.ti -1c
.RI "static final int \fBSUCCESS\fP = 200"
.br
.ti -1c
.RI "static final int \fBFORBIDDEN\fP = 403"
.br
.ti -1c
.RI "static final int \fBNOT_FOUND\fP = 404"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "\fBUser\fP \fBuser\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 Login\&.java 第 33 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.Response ()"

.PP
在文件 Login\&.java 第 41 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.Response (int code, \fBUser\fP user)"

.PP
在文件 Login\&.java 第 44 行定义\&.
.SH "成员函数说明"
.PP 
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.getCode ()"

.PP
在文件 Login\&.java 第 49 行定义\&.
.SS "\fBUser\fP com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.getUser ()"

.PP
在文件 Login\&.java 第 57 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.setCode (int code)"

.PP
在文件 Login\&.java 第 53 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.setUser (\fBUser\fP user)"

.PP
在文件 Login\&.java 第 61 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.code\fC [private]\fP"

.PP
在文件 Login\&.java 第 38 行定义\&.
.SS "final int com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.FORBIDDEN = 403\fC [static]\fP"

.PP
在文件 Login\&.java 第 35 行定义\&.
.SS "final int com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.NOT_FOUND = 404\fC [static]\fP"

.PP
在文件 Login\&.java 第 36 行定义\&.
.SS "final int com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.SUCCESS = 200\fC [static]\fP"

.PP
在文件 Login\&.java 第 34 行定义\&.
.SS "\fBUser\fP com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Response\&.user\fC [private]\fP"

.PP
在文件 Login\&.java 第 39 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
