.TH "com.angelmsger.cslaboratory.quality.article.QualityArticleItem" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.quality.article.QualityArticleItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBQualityArticleItem\fP ()"
.br
.ti -1c
.RI "\fBQualityArticleItem\fP (Long \fBid\fP, String \fBtitle\fP, String \fBgroup\fP, String \fBcontent\fP, String \fBimageURI\fP, String \fBactionURI\fP, int \fBbangCount\fP, int \fBcommentCount\fP)"
.br
.ti -1c
.RI "Long \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (Long \fBid\fP)"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "void \fBsetTitle\fP (String \fBtitle\fP)"
.br
.ti -1c
.RI "String \fBgetGroup\fP ()"
.br
.ti -1c
.RI "void \fBsetGroup\fP (String \fBgroup\fP)"
.br
.ti -1c
.RI "String \fBgetContent\fP ()"
.br
.ti -1c
.RI "void \fBsetContent\fP (String \fBcontent\fP)"
.br
.ti -1c
.RI "String \fBgetImageURI\fP ()"
.br
.ti -1c
.RI "void \fBsetImageURI\fP (String \fBimageURI\fP)"
.br
.ti -1c
.RI "String \fBgetActionURI\fP ()"
.br
.ti -1c
.RI "void \fBsetActionURI\fP (String \fBactionURI\fP)"
.br
.ti -1c
.RI "int \fBgetBangCount\fP ()"
.br
.ti -1c
.RI "void \fBsetBangCount\fP (int \fBbangCount\fP)"
.br
.ti -1c
.RI "int \fBgetCommentCount\fP ()"
.br
.ti -1c
.RI "void \fBsetCommentCount\fP (int \fBcommentCount\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "Long \fBid\fP"
.br
.ti -1c
.RI "String \fBtitle\fP"
.br
.ti -1c
.RI "String \fBgroup\fP"
.br
.ti -1c
.RI "String \fBcontent\fP"
.br
.ti -1c
.RI "String \fBimageURI\fP"
.br
.ti -1c
.RI "String \fBactionURI\fP"
.br
.ti -1c
.RI "int \fBbangCount\fP"
.br
.ti -1c
.RI "int \fBcommentCount\fP"
.br
.in -1c
.SH "详细描述"
.PP 
数据项实例类。 
.PP
在文件 QualityArticleItem\&.java 第 20 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.QualityArticleItem ()"

.PP
在文件 QualityArticleItem\&.java 第 42 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.QualityArticleItem (Long id, String title, String group, String content, String imageURI, String actionURI, int bangCount, int commentCount)"

.PP
在文件 QualityArticleItem\&.java 第 46 行定义\&.
.SH "成员函数说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getActionURI ()"

.PP
在文件 QualityArticleItem\&.java 第 98 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getBangCount ()"

.PP
在文件 QualityArticleItem\&.java 第 106 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getCommentCount ()"

.PP
在文件 QualityArticleItem\&.java 第 114 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getContent ()"

.PP
在文件 QualityArticleItem\&.java 第 82 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getGroup ()"

.PP
在文件 QualityArticleItem\&.java 第 74 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getId ()"

.PP
在文件 QualityArticleItem\&.java 第 58 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getImageURI ()"

.PP
在文件 QualityArticleItem\&.java 第 90 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.getTitle ()"

.PP
在文件 QualityArticleItem\&.java 第 66 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setActionURI (String actionURI)"

.PP
在文件 QualityArticleItem\&.java 第 102 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setBangCount (int bangCount)"

.PP
在文件 QualityArticleItem\&.java 第 110 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setCommentCount (int commentCount)"

.PP
在文件 QualityArticleItem\&.java 第 118 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setContent (String content)"

.PP
在文件 QualityArticleItem\&.java 第 86 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setGroup (String group)"

.PP
在文件 QualityArticleItem\&.java 第 78 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setId (Long id)"

.PP
在文件 QualityArticleItem\&.java 第 62 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setImageURI (String imageURI)"

.PP
在文件 QualityArticleItem\&.java 第 94 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.setTitle (String title)"

.PP
在文件 QualityArticleItem\&.java 第 70 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.actionURI\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 34 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.bangCount\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 37 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.commentCount\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 40 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.content\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 31 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.group\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 28 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.id\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 22 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.imageURI\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 33 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.article\&.QualityArticleItem\&.title\fC [private]\fP"

.PP
在文件 QualityArticleItem\&.java 第 26 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
