.TH "com.angelmsger.cslaboratory.course.course.CourseCourseItem" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.course.course.CourseCourseItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBCourseCourseItem\fP ()"
.br
.ti -1c
.RI "\fBCourseCourseItem\fP (Long \fBid\fP, String \fBimageURI\fP, String \fBtitle\fP, String \fBactionURI\fP, int \fBlearnNum\fP)"
.br
.ti -1c
.RI "Long \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (Long \fBid\fP)"
.br
.ti -1c
.RI "String \fBgetImageURI\fP ()"
.br
.ti -1c
.RI "void \fBsetImageURI\fP (String \fBimageURI\fP)"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "void \fBsetTitle\fP (String \fBtitle\fP)"
.br
.ti -1c
.RI "String \fBgetActionURI\fP ()"
.br
.ti -1c
.RI "void \fBsetActionURI\fP (String \fBactionURI\fP)"
.br
.ti -1c
.RI "int \fBgetLearnNum\fP ()"
.br
.ti -1c
.RI "void \fBsetLearnNum\fP (int \fBlearnNum\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "Long \fBid\fP"
.br
.ti -1c
.RI "String \fBimageURI\fP"
.br
.ti -1c
.RI "String \fBtitle\fP"
.br
.ti -1c
.RI "String \fBactionURI\fP"
.br
.ti -1c
.RI "int \fBlearnNum\fP"
.br
.in -1c
.SH "详细描述"
.PP 
课程项数据项实例类。 
.PP
在文件 CourseCourseItem\&.java 第 16 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.CourseCourseItem ()"

.PP
在文件 CourseCourseItem\&.java 第 32 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.CourseCourseItem (Long id, String imageURI, String title, String actionURI, int learnNum)"

.PP
在文件 CourseCourseItem\&.java 第 36 行定义\&.
.SH "成员函数说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.getActionURI ()"

.PP
在文件 CourseCourseItem\&.java 第 68 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.getId ()"

.PP
在文件 CourseCourseItem\&.java 第 44 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.getImageURI ()"

.PP
在文件 CourseCourseItem\&.java 第 52 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.getLearnNum ()"

.PP
在文件 CourseCourseItem\&.java 第 76 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.getTitle ()"

.PP
在文件 CourseCourseItem\&.java 第 60 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.setActionURI (String actionURI)"

.PP
在文件 CourseCourseItem\&.java 第 72 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.setId (Long id)"

.PP
在文件 CourseCourseItem\&.java 第 48 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.setImageURI (String imageURI)"

.PP
在文件 CourseCourseItem\&.java 第 56 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.setLearnNum (int learnNum)"

.PP
在文件 CourseCourseItem\&.java 第 80 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.setTitle (String title)"

.PP
在文件 CourseCourseItem\&.java 第 64 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.actionURI\fC [private]\fP"

.PP
在文件 CourseCourseItem\&.java 第 27 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.id\fC [private]\fP"

.PP
在文件 CourseCourseItem\&.java 第 18 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.imageURI\fC [private]\fP"

.PP
在文件 CourseCourseItem\&.java 第 21 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.learnNum\fC [private]\fP"

.PP
在文件 CourseCourseItem\&.java 第 30 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.course\&.course\&.CourseCourseItem\&.title\fC [private]\fP"

.PP
在文件 CourseCourseItem\&.java 第 24 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
