.TH "com.angelmsger.cslaboratory.forum.ForumRecyclerViewAdapter.ForumViewHolder" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.forum.ForumRecyclerViewAdapter.ForumViewHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 ViewHolder \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBForumViewHolder\fP (View view)"
.br
.ti -1c
.RI "void \fBbind\fP (final \fBForumTopicItem\fP item)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final View \fBmView\fP"
.br
.ti -1c
.RI "final CircleImageView \fBmAvatar\fP"
.br
.ti -1c
.RI "final TextView \fBmNickname\fP"
.br
.ti -1c
.RI "final TextView \fBmTitle\fP"
.br
.ti -1c
.RI "final TextView \fBmContent\fP"
.br
.ti -1c
.RI "\fBForumTopicItem\fP \fBmItem\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 ForumRecyclerViewAdapter\&.java 第 61 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.ForumViewHolder (View view)"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 69 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.bind (final \fBForumTopicItem\fP item)"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 78 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final CircleImageView com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.mAvatar"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 63 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.mContent"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 66 行定义\&.
.SS "\fBForumTopicItem\fP com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.mItem"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 67 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.mNickname"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 64 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.mTitle"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 65 行定义\&.
.SS "final View com\&.angelmsger\&.cslaboratory\&.forum\&.ForumRecyclerViewAdapter\&.ForumViewHolder\&.mView"

.PP
在文件 ForumRecyclerViewAdapter\&.java 第 62 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
