.TH "com.angelmsger.cslaboratory.daily.DailyFragment" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.daily.DailyFragment \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 Fragment , 以及 OnRefreshListener \&.
.SS "类"

.in +1c
.ti -1c
.RI "class \fBAsynLoadData\fP"
.br
.ti -1c
.RI "interface \fBOnListFragmentInteractionListener\fP"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBDailyFragment\fP ()"
.br
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "View \fBonCreateView\fP (final LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonAttach\fP (Context context)"
.br
.ti -1c
.RI "void \fBonDetach\fP ()"
.br
.ti -1c
.RI "void \fBonRefresh\fP ()"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static \fBDailyFragment\fP \fBnewInstance\fP (int columnCount)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "int \fBmColumnCount\fP = 1"
.br
.ti -1c
.RI "\fBOnListFragmentInteractionListener\fP \fBmListener\fP"
.br
.ti -1c
.RI "PullToRefreshView \fBmPullToRefreshView\fP"
.br
.ti -1c
.RI "RecyclerView \fBmRecyclerView\fP"
.br
.ti -1c
.RI "\fBDailyRecyclerViewAdapter\fP \fBmRecyclerViewAdapter\fP"
.br
.ti -1c
.RI "\fBDataSource\fP \fBmDataSource\fP"
.br
.ti -1c
.RI "\fBDailyContent\fP \fBmDailyContent\fP"
.br
.ti -1c
.RI "Handler \fBmHandler\fP"
.br
.ti -1c
.RI "\fBAsynLoadData\fP \fBmLoadDataTask\fP"
.br
.ti -1c
.RI "final int \fBmRequestLimit\fP = 16"
.br
.in -1c
.SS "静态 Private 属性"

.in +1c
.ti -1c
.RI "static final String \fBARG_COLUMN_COUNT\fP = 'column\-count'"
.br
.in -1c
.SH "详细描述"
.PP 
一个表现 Items 列表的 fragment。 包含这个 fragment 的 Activities 必须实现 \fBOnListFragmentInteractionListener\fP 接口。 
.PP
在文件 DailyFragment\&.java 第 26 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.DailyFragment ()"
为 fragment manager 预留的强制的空构造器以实例化 fragment (e\&.g\&. upon screen orientation changes)。 
.PP
在文件 DailyFragment\&.java 第 50 行定义\&.
.SH "成员函数说明"
.PP 
.SS "static \fBDailyFragment\fP com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.newInstance (int columnCount)\fC [static]\fP"

.PP
在文件 DailyFragment\&.java 第 56 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.onAttach (Context context)"

.PP
在文件 DailyFragment\&.java 第 130 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.onCreate (Bundle savedInstanceState)"

.PP
在文件 DailyFragment\&.java 第 65 行定义\&.
.SS "View com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.onCreateView (final LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"

.PP
在文件 DailyFragment\&.java 第 74 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.onDetach ()"

.PP
在文件 DailyFragment\&.java 第 142 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.onRefresh ()"

.PP
在文件 DailyFragment\&.java 第 148 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final String com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.ARG_COLUMN_COUNT = 'column\-count'\fC [static]\fP, \fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 29 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mColumnCount = 1\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 31 行定义\&.
.SS "\fBDailyContent\fP com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mDailyContent\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 39 行定义\&.
.SS "\fBDataSource\fP com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mDataSource\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 38 行定义\&.
.SS "Handler com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mHandler\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 41 行定义\&.
.SS "\fBOnListFragmentInteractionListener\fP com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mListener\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 32 行定义\&.
.SS "\fBAsynLoadData\fP com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mLoadDataTask\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 42 行定义\&.
.SS "PullToRefreshView com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mPullToRefreshView\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 34 行定义\&.
.SS "RecyclerView com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mRecyclerView\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 35 行定义\&.
.SS "\fBDailyRecyclerViewAdapter\fP com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mRecyclerViewAdapter\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 36 行定义\&.
.SS "final int com\&.angelmsger\&.cslaboratory\&.daily\&.DailyFragment\&.mRequestLimit = 16\fC [private]\fP"

.PP
在文件 DailyFragment\&.java 第 44 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
