.TH "com.angelmsger.cslaboratory.login.Login.Request" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.login.Login.Request \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBRequest\fP ()"
.br
.ti -1c
.RI "\fBRequest\fP (String \fBemail\fP, String \fBpassword\fP)"
.br
.ti -1c
.RI "String \fBgetEmail\fP ()"
.br
.ti -1c
.RI "void \fBsetEmail\fP (String \fBemail\fP)"
.br
.ti -1c
.RI "String \fBgetPassword\fP ()"
.br
.ti -1c
.RI "void \fBsetPassword\fP (String \fBpassword\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "String \fBemail\fP"
.br
.ti -1c
.RI "String \fBpassword\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 Login\&.java 第 4 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.Request ()"

.PP
在文件 Login\&.java 第 8 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.Request (String email, String password)"

.PP
在文件 Login\&.java 第 11 行定义\&.
.SH "成员函数说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.getEmail ()"

.PP
在文件 Login\&.java 第 16 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.getPassword ()"

.PP
在文件 Login\&.java 第 24 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.setEmail (String email)"

.PP
在文件 Login\&.java 第 20 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.setPassword (String password)"

.PP
在文件 Login\&.java 第 28 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.email\fC [private]\fP"

.PP
在文件 Login\&.java 第 5 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.Login\&.Request\&.password\fC [private]\fP"

.PP
在文件 Login\&.java 第 6 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
