.TH "com.angelmsger.cslaboratory.CSLaboratory" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.CSLaboratory \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 Application \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP ()"
.br
.ti -1c
.RI "void \fBonTrimMemory\fP (int level)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "ExecutorService \fBmExecutorService\fP"
.br
.ti -1c
.RI "Cache \fBmHttpCache\fP"
.br
.ti -1c
.RI "OkHttpClient \fBmHttpClient\fP"
.br
.ti -1c
.RI "OkHttpClient \fBmApiClient\fP"
.br
.ti -1c
.RI "\fBDaoSession\fP \fBmDaoSession\fP"
.br
.ti -1c
.RI "final Map< String, Object > \fBmGlobal\fP = new HashMap<>()"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 CSLaboratory\&.java 第 26 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.onCreate ()"

.PP
在文件 CSLaboratory\&.java 第 42 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.onTrimMemory (int level)"

.PP
在文件 CSLaboratory\&.java 第 73 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "OkHttpClient com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.mApiClient"

.PP
在文件 CSLaboratory\&.java 第 33 行定义\&.
.SS "\fBDaoSession\fP com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.mDaoSession"

.PP
在文件 CSLaboratory\&.java 第 36 行定义\&.
.SS "ExecutorService com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.mExecutorService"

.PP
在文件 CSLaboratory\&.java 第 27 行定义\&.
.SS "final Map<String, Object> com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.mGlobal = new HashMap<>()"

.PP
在文件 CSLaboratory\&.java 第 39 行定义\&.
.SS "Cache com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.mHttpCache"

.PP
在文件 CSLaboratory\&.java 第 29 行定义\&.
.SS "OkHttpClient com\&.angelmsger\&.cslaboratory\&.CSLaboratory\&.mHttpClient"

.PP
在文件 CSLaboratory\&.java 第 30 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
