.TH "com.angelmsger.cslaboratory.quality" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.quality \- 
.SH SYNOPSIS
.br
.PP
.SS "包"

.in +1c
.ti -1c
.RI "package \fBad\fP"
.br
.ti -1c
.RI "package \fBarticle\fP"
.br
.ti -1c
.RI "package \fBcategory\fP"
.br
.in -1c
.SS "类"

.in +1c
.ti -1c
.RI "class \fBQualityContent\fP"
.br
.ti -1c
.RI "class \fBQualityFragment\fP"
.br
.ti -1c
.RI "class \fBQualityRecyclerViewAdapter\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
