.TH "com.angelmsger.cslaboratory.source.LocalDataSource" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.source.LocalDataSource \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "Login\&.Response \fBattemptLogin\fP (Login\&.Request request)"
.br
.ti -1c
.RI "\fBCourseContent\fP \fBgetCourseContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBDailyContent\fP \fBgetDailyContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBForumContent\fP \fBgetForumContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBQualityContent\fP \fBgetQualityContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBTopologyContent\fP \fBgetTopologyContent\fP (final int offset, final int limit)"
.br
.in -1c
.SH "详细描述"
.PP 
实现数据源接口，数据源为本地缓存数据库 
.PP
在文件 LocalDataSource\&.java 第 14 行定义\&.
.SH "成员函数说明"
.PP 
.SS "Login\&.Response com\&.angelmsger\&.cslaboratory\&.source\&.LocalDataSource\&.attemptLogin (Login\&.Request request)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 LocalDataSource\&.java 第 16 行定义\&.
.SS "\fBCourseContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.LocalDataSource\&.getCourseContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 LocalDataSource\&.java 第 21 行定义\&.
.SS "\fBDailyContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.LocalDataSource\&.getDailyContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 LocalDataSource\&.java 第 26 行定义\&.
.SS "\fBForumContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.LocalDataSource\&.getForumContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 LocalDataSource\&.java 第 31 行定义\&.
.SS "\fBQualityContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.LocalDataSource\&.getQualityContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 LocalDataSource\&.java 第 36 行定义\&.
.SS "\fBTopologyContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.LocalDataSource\&.getTopologyContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 LocalDataSource\&.java 第 41 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
