.TH "com.angelmsger.cslaboratory.dao.DaoMaster.OpenHelper" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.dao.DaoMaster.OpenHelper \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 DatabaseOpenHelper \&.
.PP
被 \fBcom\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.DevOpenHelper\fP 继承\&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBOpenHelper\fP (Context context, String name)"
.br
.ti -1c
.RI "\fBOpenHelper\fP (Context context, String name, CursorFactory factory)"
.br
.ti -1c
.RI "void \fBonCreate\fP (Database db)"
.br
.in -1c
.SH "详细描述"
.PP 
Calls \fBcreateAllTables(Database, boolean)\fP in \fBonCreate(Database)\fP - 
.PP
在文件 DaoMaster\&.java 第 86 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.OpenHelper\&.OpenHelper (Context context, String name)"

.PP
在文件 DaoMaster\&.java 第 87 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.OpenHelper\&.OpenHelper (Context context, String name, CursorFactory factory)"

.PP
在文件 DaoMaster\&.java 第 91 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.OpenHelper\&.onCreate (Database db)"

.PP
在文件 DaoMaster\&.java 第 96 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
