.TH "com.angelmsger.cslaboratory.daily.DailyRecyclerViewAdapter.DailyViewHolder" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.daily.DailyRecyclerViewAdapter.DailyViewHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 ViewHolder \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBDailyViewHolder\fP (View view)"
.br
.ti -1c
.RI "void \fBbind\fP (final \fBDailyArticleItem\fP item)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final View \fBmView\fP"
.br
.ti -1c
.RI "final ImageView \fBmImage\fP"
.br
.ti -1c
.RI "final TextView \fBmTitle\fP"
.br
.ti -1c
.RI "final TextView \fBmContent\fP"
.br
.ti -1c
.RI "\fBDailyArticleItem\fP \fBmItem\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 DailyRecyclerViewAdapter\&.java 第 62 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.daily\&.DailyRecyclerViewAdapter\&.DailyViewHolder\&.DailyViewHolder (View view)"

.PP
在文件 DailyRecyclerViewAdapter\&.java 第 69 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.daily\&.DailyRecyclerViewAdapter\&.DailyViewHolder\&.bind (final \fBDailyArticleItem\fP item)"

.PP
在文件 DailyRecyclerViewAdapter\&.java 第 77 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.daily\&.DailyRecyclerViewAdapter\&.DailyViewHolder\&.mContent"

.PP
在文件 DailyRecyclerViewAdapter\&.java 第 66 行定义\&.
.SS "final ImageView com\&.angelmsger\&.cslaboratory\&.daily\&.DailyRecyclerViewAdapter\&.DailyViewHolder\&.mImage"

.PP
在文件 DailyRecyclerViewAdapter\&.java 第 64 行定义\&.
.SS "\fBDailyArticleItem\fP com\&.angelmsger\&.cslaboratory\&.daily\&.DailyRecyclerViewAdapter\&.DailyViewHolder\&.mItem"

.PP
在文件 DailyRecyclerViewAdapter\&.java 第 67 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.daily\&.DailyRecyclerViewAdapter\&.DailyViewHolder\&.mTitle"

.PP
在文件 DailyRecyclerViewAdapter\&.java 第 65 行定义\&.
.SS "final View com\&.angelmsger\&.cslaboratory\&.daily\&.DailyRecyclerViewAdapter\&.DailyViewHolder\&.mView"

.PP
在文件 DailyRecyclerViewAdapter\&.java 第 63 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
