.TH "com.angelmsger.cslaboratory.quality.category.QualityCategoryItem" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.quality.category.QualityCategoryItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBQualityCategoryItem\fP ()"
.br
.ti -1c
.RI "\fBQualityCategoryItem\fP (Long \fBid\fP, String \fBtitle\fP, String \fBimageURI\fP)"
.br
.ti -1c
.RI "Long \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (Long \fBid\fP)"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "void \fBsetTitle\fP (String \fBtitle\fP)"
.br
.ti -1c
.RI "String \fBgetImageURI\fP ()"
.br
.ti -1c
.RI "void \fBsetImageURI\fP (String \fBimageURI\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "Long \fBid\fP"
.br
.ti -1c
.RI "String \fBtitle\fP"
.br
.ti -1c
.RI "String \fBimageURI\fP"
.br
.in -1c
.SH "详细描述"
.PP 
数据项实例类。 
.PP
在文件 QualityCategoryItem\&.java 第 14 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.QualityCategoryItem ()"

.PP
在文件 QualityCategoryItem\&.java 第 25 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.QualityCategoryItem (Long id, String title, String imageURI)"

.PP
在文件 QualityCategoryItem\&.java 第 29 行定义\&.
.SH "成员函数说明"
.PP 
.SS "Long com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.getId ()"

.PP
在文件 QualityCategoryItem\&.java 第 35 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.getImageURI ()"

.PP
在文件 QualityCategoryItem\&.java 第 51 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.getTitle ()"

.PP
在文件 QualityCategoryItem\&.java 第 43 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.setId (Long id)"

.PP
在文件 QualityCategoryItem\&.java 第 39 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.setImageURI (String imageURI)"

.PP
在文件 QualityCategoryItem\&.java 第 55 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.setTitle (String title)"

.PP
在文件 QualityCategoryItem\&.java 第 47 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "Long com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.id\fC [private]\fP"

.PP
在文件 QualityCategoryItem\&.java 第 16 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.imageURI\fC [private]\fP"

.PP
在文件 QualityCategoryItem\&.java 第 23 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.quality\&.category\&.QualityCategoryItem\&.title\fC [private]\fP"

.PP
在文件 QualityCategoryItem\&.java 第 20 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
