.TH "com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.ADViewHolder" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.ADViewHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 ViewHolder \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBADViewHolder\fP (View view)"
.br
.ti -1c
.RI "void \fBbind\fP (List< \fBQualityADItem\fP > items)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final View \fBmView\fP"
.br
.ti -1c
.RI "final ViewPager \fBmContainer\fP"
.br
.ti -1c
.RI "final CircleIndicator \fBmIndicator\fP"
.br
.ti -1c
.RI "List< \fBQualityADItem\fP > \fBmItems\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 QualityRecyclerViewAdapter\&.java 第 120 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADViewHolder\&.ADViewHolder (View view)"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 126 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADViewHolder\&.bind (List< \fBQualityADItem\fP > items)"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 133 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final ViewPager com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADViewHolder\&.mContainer"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 122 行定义\&.
.SS "final CircleIndicator com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADViewHolder\&.mIndicator"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 123 行定义\&.
.SS "List<\fBQualityADItem\fP> com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADViewHolder\&.mItems"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 124 行定义\&.
.SS "final View com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADViewHolder\&.mView"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 121 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
