.TH "com.angelmsger.cslaboratory.quality.QualityFragment" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.quality.QualityFragment \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 Fragment , 以及 OnRefreshListener \&.
.SS "类"

.in +1c
.ti -1c
.RI "class \fBAsynLoadData\fP"
.br
.ti -1c
.RI "interface \fBOnListFragmentInteractionListener\fP"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBQualityFragment\fP ()"
.br
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "View \fBonCreateView\fP (final LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonAttach\fP (Context context)"
.br
.ti -1c
.RI "void \fBonDetach\fP ()"
.br
.ti -1c
.RI "void \fBonRefresh\fP ()"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static \fBQualityFragment\fP \fBnewInstance\fP (int columnCount)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "int \fBmColumnCount\fP = 1"
.br
.ti -1c
.RI "\fBOnListFragmentInteractionListener\fP \fBmListener\fP"
.br
.ti -1c
.RI "PullToRefreshView \fBmPullToRefreshView\fP"
.br
.ti -1c
.RI "RecyclerView \fBmRecyclerView\fP"
.br
.ti -1c
.RI "\fBQualityRecyclerViewAdapter\fP \fBmRecyclerViewAdapter\fP"
.br
.ti -1c
.RI "final \fBDataSource\fP \fBmDataSource\fP"
.br
.ti -1c
.RI "\fBQualityContent\fP \fBmQualityContent\fP"
.br
.ti -1c
.RI "Handler \fBmHandler\fP"
.br
.ti -1c
.RI "\fBAsynLoadData\fP \fBmLoadDataTask\fP"
.br
.ti -1c
.RI "final int \fBmRequestLimit\fP = 16"
.br
.in -1c
.SS "静态 Private 属性"

.in +1c
.ti -1c
.RI "static final String \fBARG_COLUMN_COUNT\fP = 'column\-count'"
.br
.in -1c
.SH "详细描述"
.PP 
一个表现 Items 列表的 fragment。 包含这个 fragment 的 Activities 必须实现 \fBOnListFragmentInteractionListener\fP 接口。 
.PP
在文件 QualityFragment\&.java 第 29 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.QualityFragment ()"
为 fragment manager 预留的强制的空构造器以实例化 fragment (e\&.g\&. upon screen orientation changes)。 
.PP
在文件 QualityFragment\&.java 第 54 行定义\&.
.SH "成员函数说明"
.PP 
.SS "static \fBQualityFragment\fP com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.newInstance (int columnCount)\fC [static]\fP"

.PP
在文件 QualityFragment\&.java 第 62 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.onAttach (Context context)"

.PP
在文件 QualityFragment\&.java 第 149 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.onCreate (Bundle savedInstanceState)"

.PP
在文件 QualityFragment\&.java 第 71 行定义\&.
.SS "View com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.onCreateView (final LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)"

.PP
在文件 QualityFragment\&.java 第 80 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.onDetach ()"

.PP
在文件 QualityFragment\&.java 第 160 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.onRefresh ()"

.PP
在文件 QualityFragment\&.java 第 166 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final String com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.ARG_COLUMN_COUNT = 'column\-count'\fC [static]\fP, \fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 32 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mColumnCount = 1\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 34 行定义\&.
.SS "final \fBDataSource\fP com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mDataSource\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 41 行定义\&.
.SS "Handler com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mHandler\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 44 行定义\&.
.SS "\fBOnListFragmentInteractionListener\fP com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mListener\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 35 行定义\&.
.SS "\fBAsynLoadData\fP com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mLoadDataTask\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 45 行定义\&.
.SS "PullToRefreshView com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mPullToRefreshView\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 37 行定义\&.
.SS "\fBQualityContent\fP com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mQualityContent\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 42 行定义\&.
.SS "RecyclerView com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mRecyclerView\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 38 行定义\&.
.SS "\fBQualityRecyclerViewAdapter\fP com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mRecyclerViewAdapter\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 39 行定义\&.
.SS "final int com\&.angelmsger\&.cslaboratory\&.quality\&.QualityFragment\&.mRequestLimit = 16\fC [private]\fP"

.PP
在文件 QualityFragment\&.java 第 47 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
