.TH "com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 Adapter< RecyclerView\&.ViewHolder > \&.
.SS "类"

.in +1c
.ti -1c
.RI "class \fBClassViewHolder\fP"
.br
.ti -1c
.RI "class \fBCourseViewHolder\fP"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBCourseRecyclerViewAdapter\fP (List< \fBCourseCategoryItem\fP > courseCourseCategoryItems, List< \fBCourseCourseItem\fP > courseCourseItems, LayoutInflater inflater, \fBOnListFragmentInteractionListener\fP listener)"
.br
.ti -1c
.RI "int \fBgetItemViewType\fP (int position)"
.br
.ti -1c
.RI "ViewHolder \fBonCreateViewHolder\fP (ViewGroup parent, int viewType)"
.br
.ti -1c
.RI "void \fBonBindViewHolder\fP (final ViewHolder holder, int position)"
.br
.ti -1c
.RI "int \fBgetItemCount\fP ()"
.br
.ti -1c
.RI "int \fBgetNextRequestOffset\fP ()"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "final List< \fBCourseCategoryItem\fP > \fBmCourseCategoryItems\fP"
.br
.ti -1c
.RI "final List< \fBCourseCourseItem\fP > \fBmCourseCourseItems\fP"
.br
.ti -1c
.RI "final LayoutInflater \fBmInflater\fP"
.br
.ti -1c
.RI "final \fBOnListFragmentInteractionListener\fP \fBmListener\fP"
.br
.in -1c
.SH "详细描述"
.PP 
\fBRecyclerView\&.Adapter\fP 可以展示一些 \fBCourseCourseItem\fP 并且调用指定的 \fBOnListFragmentInteractionListener\fP\&. TODO: 替换为自定义代码段。 
.PP
在文件 CourseRecyclerViewAdapter\&.java 第 27 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseRecyclerViewAdapter (List< \fBCourseCategoryItem\fP > courseCourseCategoryItems, List< \fBCourseCourseItem\fP > courseCourseItems, LayoutInflater inflater, \fBOnListFragmentInteractionListener\fP listener)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 34 行定义\&.
.SH "成员函数说明"
.PP 
.SS "int com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.getItemCount ()"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 80 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.getItemViewType (int position)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 45 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.getNextRequestOffset ()"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 85 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.onBindViewHolder (final ViewHolder holder, int position)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 69 行定义\&.
.SS "ViewHolder com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.onCreateViewHolder (ViewGroup parent, int viewType)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 55 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final List<\fBCourseCategoryItem\fP> com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.mCourseCategoryItems\fC [private]\fP"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 29 行定义\&.
.SS "final List<\fBCourseCourseItem\fP> com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.mCourseCourseItems\fC [private]\fP"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 30 行定义\&.
.SS "final LayoutInflater com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.mInflater\fC [private]\fP"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 31 行定义\&.
.SS "final \fBOnListFragmentInteractionListener\fP com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.mListener\fC [private]\fP"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 32 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
