.TH "com.angelmsger.cslaboratory.topology.field.TopologyFieldItem" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.topology.field.TopologyFieldItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBTopologyFieldItem\fP ()"
.br
.ti -1c
.RI "\fBTopologyFieldItem\fP (Long \fBid\fP, String \fBbackgroundURI\fP, String \fBtitle\fP, String \fBcontent\fP, String \fBimageURI\fP)"
.br
.ti -1c
.RI "Long \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (Long \fBid\fP)"
.br
.ti -1c
.RI "String \fBgetBackgroundURI\fP ()"
.br
.ti -1c
.RI "void \fBsetBackgroundURI\fP (String \fBbackgroundURI\fP)"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "void \fBsetTitle\fP (String \fBtitle\fP)"
.br
.ti -1c
.RI "String \fBgetContent\fP ()"
.br
.ti -1c
.RI "void \fBsetContent\fP (String \fBcontent\fP)"
.br
.ti -1c
.RI "String \fBgetImageURI\fP ()"
.br
.ti -1c
.RI "void \fBsetImageURI\fP (String \fBimageURI\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "Long \fBid\fP"
.br
.ti -1c
.RI "String \fBbackgroundURI\fP"
.br
.ti -1c
.RI "String \fBtitle\fP"
.br
.ti -1c
.RI "String \fBcontent\fP"
.br
.ti -1c
.RI "String \fBimageURI\fP"
.br
.in -1c
.SH "详细描述"
.PP 
数据项实例类。 
.PP
在文件 TopologyFieldItem\&.java 第 16 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.TopologyFieldItem ()"

.PP
在文件 TopologyFieldItem\&.java 第 32 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.TopologyFieldItem (Long id, String backgroundURI, String title, String content, String imageURI)"

.PP
在文件 TopologyFieldItem\&.java 第 36 行定义\&.
.SH "成员函数说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.getBackgroundURI ()"

.PP
在文件 TopologyFieldItem\&.java 第 53 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.getContent ()"

.PP
在文件 TopologyFieldItem\&.java 第 69 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.getId ()"

.PP
在文件 TopologyFieldItem\&.java 第 45 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.getImageURI ()"

.PP
在文件 TopologyFieldItem\&.java 第 77 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.getTitle ()"

.PP
在文件 TopologyFieldItem\&.java 第 61 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.setBackgroundURI (String backgroundURI)"

.PP
在文件 TopologyFieldItem\&.java 第 57 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.setContent (String content)"

.PP
在文件 TopologyFieldItem\&.java 第 73 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.setId (Long id)"

.PP
在文件 TopologyFieldItem\&.java 第 49 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.setImageURI (String imageURI)"

.PP
在文件 TopologyFieldItem\&.java 第 81 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.setTitle (String title)"

.PP
在文件 TopologyFieldItem\&.java 第 65 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.backgroundURI\fC [private]\fP"

.PP
在文件 TopologyFieldItem\&.java 第 21 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.content\fC [private]\fP"

.PP
在文件 TopologyFieldItem\&.java 第 27 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.id\fC [private]\fP"

.PP
在文件 TopologyFieldItem\&.java 第 18 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.imageURI\fC [private]\fP"

.PP
在文件 TopologyFieldItem\&.java 第 30 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.topology\&.field\&.TopologyFieldItem\&.title\fC [private]\fP"

.PP
在文件 TopologyFieldItem\&.java 第 24 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
