.TH "com.angelmsger.cslaboratory.dao.ForumTopicItemDao.Properties" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.dao.ForumTopicItemDao.Properties \- 
.SH SYNOPSIS
.br
.PP
.SS "静态 Public 属性"

.in +1c
.ti -1c
.RI "static final Property \fBId\fP = new Property(0, Long\&.class, 'id', true, '_id')"
.br
.ti -1c
.RI "static final Property \fBAvatarURI\fP = new Property(1, String\&.class, 'avatarURI', false, 'AVATAR_URI')"
.br
.ti -1c
.RI "static final Property \fBNickname\fP = new Property(2, String\&.class, 'nickname', false, 'NICKNAME')"
.br
.ti -1c
.RI "static final Property \fBTitle\fP = new Property(3, String\&.class, 'title', false, 'TITLE')"
.br
.ti -1c
.RI "static final Property \fBContent\fP = new Property(4, String\&.class, 'content', false, 'CONTENT')"
.br
.in -1c
.SH "详细描述"
.PP 
\fBProperties\fP of entity ForumTopicItem\&.
.br
 Can be used for QueryBuilder and for referencing column names\&. 
.PP
在文件 ForumTopicItemDao\&.java 第 26 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final Property com\&.angelmsger\&.cslaboratory\&.dao\&.ForumTopicItemDao\&.Properties\&.AvatarURI = new Property(1, String\&.class, 'avatarURI', false, 'AVATAR_URI')\fC [static]\fP"

.PP
在文件 ForumTopicItemDao\&.java 第 28 行定义\&.
.SS "final Property com\&.angelmsger\&.cslaboratory\&.dao\&.ForumTopicItemDao\&.Properties\&.Content = new Property(4, String\&.class, 'content', false, 'CONTENT')\fC [static]\fP"

.PP
在文件 ForumTopicItemDao\&.java 第 31 行定义\&.
.SS "final Property com\&.angelmsger\&.cslaboratory\&.dao\&.ForumTopicItemDao\&.Properties\&.Id = new Property(0, Long\&.class, 'id', true, '_id')\fC [static]\fP"

.PP
在文件 ForumTopicItemDao\&.java 第 27 行定义\&.
.SS "final Property com\&.angelmsger\&.cslaboratory\&.dao\&.ForumTopicItemDao\&.Properties\&.Nickname = new Property(2, String\&.class, 'nickname', false, 'NICKNAME')\fC [static]\fP"

.PP
在文件 ForumTopicItemDao\&.java 第 29 行定义\&.
.SS "final Property com\&.angelmsger\&.cslaboratory\&.dao\&.ForumTopicItemDao\&.Properties\&.Title = new Property(3, String\&.class, 'title', false, 'TITLE')\fC [static]\fP"

.PP
在文件 ForumTopicItemDao\&.java 第 30 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
