.TH "com.angelmsger.cslaboratory.dao.DaoSession" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.dao.DaoSession \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 AbstractDaoSession \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBDaoSession\fP (Database db, IdentityScopeType type, Map< Class<? extends AbstractDao<?, ?>>, DaoConfig > daoConfigMap)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBCourseCourseItemDao\fP \fBgetCourseCourseItemDao\fP ()"
.br
.ti -1c
.RI "\fBCourseCategoryItemDao\fP \fBgetCourseCategoryItemDao\fP ()"
.br
.ti -1c
.RI "\fBCourseSubclassItemDao\fP \fBgetCourseSubclassItemDao\fP ()"
.br
.ti -1c
.RI "\fBDailyArticleItemDao\fP \fBgetDailyArticleItemDao\fP ()"
.br
.ti -1c
.RI "\fBForumTopicItemDao\fP \fBgetForumTopicItemDao\fP ()"
.br
.ti -1c
.RI "\fBQualityADItemDao\fP \fBgetQualityADItemDao\fP ()"
.br
.ti -1c
.RI "\fBQualityArticleItemDao\fP \fBgetQualityArticleItemDao\fP ()"
.br
.ti -1c
.RI "\fBQualityCategoryItemDao\fP \fBgetQualityCategoryItemDao\fP ()"
.br
.ti -1c
.RI "\fBTopologyFieldItemDao\fP \fBgetTopologyFieldItemDao\fP ()"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "final DaoConfig \fBcourseCourseItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBcourseCategoryItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBcourseSubclassItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBdailyArticleItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBforumTopicItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBqualityADItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBqualityArticleItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBqualityCategoryItemDaoConfig\fP"
.br
.ti -1c
.RI "final DaoConfig \fBtopologyFieldItemDaoConfig\fP"
.br
.ti -1c
.RI "final \fBCourseCourseItemDao\fP \fBcourseCourseItemDao\fP"
.br
.ti -1c
.RI "final \fBCourseCategoryItemDao\fP \fBcourseCategoryItemDao\fP"
.br
.ti -1c
.RI "final \fBCourseSubclassItemDao\fP \fBcourseSubclassItemDao\fP"
.br
.ti -1c
.RI "final \fBDailyArticleItemDao\fP \fBdailyArticleItemDao\fP"
.br
.ti -1c
.RI "final \fBForumTopicItemDao\fP \fBforumTopicItemDao\fP"
.br
.ti -1c
.RI "final \fBQualityADItemDao\fP \fBqualityADItemDao\fP"
.br
.ti -1c
.RI "final \fBQualityArticleItemDao\fP \fBqualityArticleItemDao\fP"
.br
.ti -1c
.RI "final \fBQualityCategoryItemDao\fP \fBqualityCategoryItemDao\fP"
.br
.ti -1c
.RI "final \fBTopologyFieldItemDao\fP \fBtopologyFieldItemDao\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.PP
\fB参见:\fP
.RS 4
org\&.greenrobot\&.greendao\&.AbstractDaoSession 
.RE
.PP

.PP
在文件 DaoSession\&.java 第 38 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.DaoSession (Database db, IdentityScopeType type, Map< Class<? extends AbstractDao<?, ?>>, DaoConfig > daoConfigMap)"

.PP
在文件 DaoSession\&.java 第 60 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.clear ()"

.PP
在文件 DaoSession\&.java 第 112 行定义\&.
.SS "\fBCourseCategoryItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getCourseCategoryItemDao ()"

.PP
在文件 DaoSession\&.java 第 128 行定义\&.
.SS "\fBCourseCourseItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getCourseCourseItemDao ()"

.PP
在文件 DaoSession\&.java 第 124 行定义\&.
.SS "\fBCourseSubclassItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getCourseSubclassItemDao ()"

.PP
在文件 DaoSession\&.java 第 132 行定义\&.
.SS "\fBDailyArticleItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getDailyArticleItemDao ()"

.PP
在文件 DaoSession\&.java 第 136 行定义\&.
.SS "\fBForumTopicItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getForumTopicItemDao ()"

.PP
在文件 DaoSession\&.java 第 140 行定义\&.
.SS "\fBQualityADItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getQualityADItemDao ()"

.PP
在文件 DaoSession\&.java 第 144 行定义\&.
.SS "\fBQualityArticleItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getQualityArticleItemDao ()"

.PP
在文件 DaoSession\&.java 第 148 行定义\&.
.SS "\fBQualityCategoryItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getQualityCategoryItemDao ()"

.PP
在文件 DaoSession\&.java 第 152 行定义\&.
.SS "\fBTopologyFieldItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.getTopologyFieldItemDao ()"

.PP
在文件 DaoSession\&.java 第 156 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final \fBCourseCategoryItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.courseCategoryItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 51 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.courseCategoryItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 41 行定义\&.
.SS "final \fBCourseCourseItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.courseCourseItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 50 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.courseCourseItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 40 行定义\&.
.SS "final \fBCourseSubclassItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.courseSubclassItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 52 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.courseSubclassItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 42 行定义\&.
.SS "final \fBDailyArticleItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.dailyArticleItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 53 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.dailyArticleItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 43 行定义\&.
.SS "final \fBForumTopicItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.forumTopicItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 54 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.forumTopicItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 44 行定义\&.
.SS "final \fBQualityADItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.qualityADItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 55 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.qualityADItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 45 行定义\&.
.SS "final \fBQualityArticleItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.qualityArticleItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 56 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.qualityArticleItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 46 行定义\&.
.SS "final \fBQualityCategoryItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.qualityCategoryItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 57 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.qualityCategoryItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 47 行定义\&.
.SS "final \fBTopologyFieldItemDao\fP com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.topologyFieldItemDao\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 58 行定义\&.
.SS "final DaoConfig com\&.angelmsger\&.cslaboratory\&.dao\&.DaoSession\&.topologyFieldItemDaoConfig\fC [private]\fP"

.PP
在文件 DaoSession\&.java 第 48 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
