.TH "com.angelmsger.cslaboratory.dao.QualityCategoryItemDao" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.dao.QualityCategoryItemDao \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 AbstractDao< QualityCategoryItem, Long > \&.
.SS "类"

.in +1c
.ti -1c
.RI "class \fBProperties\fP"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBQualityCategoryItemDao\fP (DaoConfig config)"
.br
.ti -1c
.RI "\fBQualityCategoryItemDao\fP (DaoConfig config, \fBDaoSession\fP daoSession)"
.br
.ti -1c
.RI "Long \fBreadKey\fP (Cursor cursor, int offset)"
.br
.ti -1c
.RI "\fBQualityCategoryItem\fP \fBreadEntity\fP (Cursor cursor, int offset)"
.br
.ti -1c
.RI "void \fBreadEntity\fP (Cursor cursor, \fBQualityCategoryItem\fP entity, int offset)"
.br
.ti -1c
.RI "Long \fBgetKey\fP (\fBQualityCategoryItem\fP entity)"
.br
.ti -1c
.RI "boolean \fBhasKey\fP (\fBQualityCategoryItem\fP entity)"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static void \fBcreateTable\fP (Database db, boolean ifNotExists)"
.br
.ti -1c
.RI "static void \fBdropTable\fP (Database db, boolean ifExists)"
.br
.in -1c
.SS "静态 Public 属性"

.in +1c
.ti -1c
.RI "static final String \fBTABLENAME\fP = 'quality_categories'"
.br
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "final void \fBbindValues\fP (DatabaseStatement stmt, \fBQualityCategoryItem\fP entity)"
.br
.ti -1c
.RI "final void \fBbindValues\fP (SQLiteStatement stmt, \fBQualityCategoryItem\fP entity)"
.br
.ti -1c
.RI "final Long \fBupdateKeyAfterInsert\fP (\fBQualityCategoryItem\fP entity, long rowId)"
.br
.ti -1c
.RI "final boolean \fBisEntityUpdateable\fP ()"
.br
.in -1c
.SH "详细描述"
.PP 
DAO for table 'quality_categories'\&. 
.PP
在文件 QualityCategoryItemDao\&.java 第 18 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.QualityCategoryItemDao (DaoConfig config)"

.PP
在文件 QualityCategoryItemDao\&.java 第 33 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.QualityCategoryItemDao (DaoConfig config, \fBDaoSession\fP daoSession)"

.PP
在文件 QualityCategoryItemDao\&.java 第 37 行定义\&.
.SH "成员函数说明"
.PP 
.SS "final void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.bindValues (DatabaseStatement stmt, \fBQualityCategoryItem\fP entity)\fC [protected]\fP"

.PP
在文件 QualityCategoryItemDao\&.java 第 57 行定义\&.
.SS "final void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.bindValues (SQLiteStatement stmt, \fBQualityCategoryItem\fP entity)\fC [protected]\fP"

.PP
在文件 QualityCategoryItemDao\&.java 第 69 行定义\&.
.SS "static void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.createTable (Database db, boolean ifNotExists)\fC [static]\fP"
Creates the underlying database table\&. 
.PP
在文件 QualityCategoryItemDao\&.java 第 42 行定义\&.
.SS "static void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.dropTable (Database db, boolean ifExists)\fC [static]\fP"
Drops the underlying database table\&. 
.PP
在文件 QualityCategoryItemDao\&.java 第 51 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.getKey (\fBQualityCategoryItem\fP entity)"

.PP
在文件 QualityCategoryItemDao\&.java 第 109 行定义\&.
.SS "boolean com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.hasKey (\fBQualityCategoryItem\fP entity)"

.PP
在文件 QualityCategoryItemDao\&.java 第 118 行定义\&.
.SS "final boolean com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.isEntityUpdateable ()\fC [protected]\fP"

.PP
在文件 QualityCategoryItemDao\&.java 第 123 行定义\&.
.SS "\fBQualityCategoryItem\fP com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.readEntity (Cursor cursor, int offset)"

.PP
在文件 QualityCategoryItemDao\&.java 第 86 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.readEntity (Cursor cursor, \fBQualityCategoryItem\fP entity, int offset)"

.PP
在文件 QualityCategoryItemDao\&.java 第 96 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.readKey (Cursor cursor, int offset)"

.PP
在文件 QualityCategoryItemDao\&.java 第 81 行定义\&.
.SS "final Long com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.updateKeyAfterInsert (\fBQualityCategoryItem\fP entity, long rowId)\fC [protected]\fP"

.PP
在文件 QualityCategoryItemDao\&.java 第 103 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final String com\&.angelmsger\&.cslaboratory\&.dao\&.QualityCategoryItemDao\&.TABLENAME = 'quality_categories'\fC [static]\fP"

.PP
在文件 QualityCategoryItemDao\&.java 第 20 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
