.TH "com.angelmsger.cslaboratory.login.User.Base" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.login.User.Base \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBBase\fP ()"
.br
.ti -1c
.RI "\fBBase\fP (String \fBid\fP, String \fBnickname\fP, String \fBimageURI\fP, String \fBavatarURI\fP)"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String \fBid\fP)"
.br
.ti -1c
.RI "String \fBgetNickname\fP ()"
.br
.ti -1c
.RI "void \fBsetNickname\fP (String \fBnickname\fP)"
.br
.ti -1c
.RI "String \fBgetImageURI\fP ()"
.br
.ti -1c
.RI "void \fBsetImageURI\fP (String \fBimageURI\fP)"
.br
.ti -1c
.RI "String \fBgetAvatarURI\fP ()"
.br
.ti -1c
.RI "void \fBsetAvatarURI\fP (String \fBavatarURI\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "String \fBid\fP"
.br
.ti -1c
.RI "String \fBnickname\fP"
.br
.ti -1c
.RI "String \fBimageURI\fP"
.br
.ti -1c
.RI "String \fBavatarURI\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 User\&.java 第 31 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.Base ()"

.PP
在文件 User\&.java 第 37 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.Base (String id, String nickname, String imageURI, String avatarURI)"

.PP
在文件 User\&.java 第 40 行定义\&.
.SH "成员函数说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.getAvatarURI ()"

.PP
在文件 User\&.java 第 71 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.getId ()"

.PP
在文件 User\&.java 第 47 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.getImageURI ()"

.PP
在文件 User\&.java 第 63 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.getNickname ()"

.PP
在文件 User\&.java 第 55 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.setAvatarURI (String avatarURI)"

.PP
在文件 User\&.java 第 75 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.setId (String id)"

.PP
在文件 User\&.java 第 51 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.setImageURI (String imageURI)"

.PP
在文件 User\&.java 第 67 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.setNickname (String nickname)"

.PP
在文件 User\&.java 第 59 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.avatarURI\fC [private]\fP"

.PP
在文件 User\&.java 第 35 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.id\fC [private]\fP"

.PP
在文件 User\&.java 第 32 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.imageURI\fC [private]\fP"

.PP
在文件 User\&.java 第 34 行定义\&.
.SS "String com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Base\&.nickname\fC [private]\fP"

.PP
在文件 User\&.java 第 33 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
