.TH "com.angelmsger.cslaboratory.shared.ScrollingActivity" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.shared.ScrollingActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 AppCompatActivity \&.
.SS "静态 Public 属性"

.in +1c
.ti -1c
.RI "static final String \fBIMAGE_URI\fP = 'ImageURI'"
.br
.ti -1c
.RI "static final String \fBARTICLE_TITLE\fP = 'Title'"
.br
.ti -1c
.RI "static final String \fBARTICLE_CONTENT\fP = 'Content'"
.br
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 ScrollingActivity\&.java 第 15 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.shared\&.ScrollingActivity\&.onCreate (Bundle savedInstanceState)\fC [protected]\fP"

.PP
在文件 ScrollingActivity\&.java 第 21 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final String com\&.angelmsger\&.cslaboratory\&.shared\&.ScrollingActivity\&.ARTICLE_CONTENT = 'Content'\fC [static]\fP"

.PP
在文件 ScrollingActivity\&.java 第 18 行定义\&.
.SS "final String com\&.angelmsger\&.cslaboratory\&.shared\&.ScrollingActivity\&.ARTICLE_TITLE = 'Title'\fC [static]\fP"

.PP
在文件 ScrollingActivity\&.java 第 17 行定义\&.
.SS "final String com\&.angelmsger\&.cslaboratory\&.shared\&.ScrollingActivity\&.IMAGE_URI = 'ImageURI'\fC [static]\fP"

.PP
在文件 ScrollingActivity\&.java 第 16 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
