.TH "com.angelmsger.cslaboratory.dao.DaoMaster.DevOpenHelper" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.dao.DaoMaster.DevOpenHelper \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 \fBcom\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.OpenHelper\fP \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBDevOpenHelper\fP (Context context, String name)"
.br
.ti -1c
.RI "\fBDevOpenHelper\fP (Context context, String name, CursorFactory factory)"
.br
.ti -1c
.RI "void \fBonUpgrade\fP (Database db, int oldVersion, int newVersion)"
.br
.in -1c
.SH "详细描述"
.PP 
WARNING: Drops all table on Upgrade! Use only during development\&. 
.PP
在文件 DaoMaster\&.java 第 103 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.DevOpenHelper\&.DevOpenHelper (Context context, String name)"

.PP
在文件 DaoMaster\&.java 第 104 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.DevOpenHelper\&.DevOpenHelper (Context context, String name, CursorFactory factory)"

.PP
在文件 DaoMaster\&.java 第 108 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.dao\&.DaoMaster\&.DevOpenHelper\&.onUpgrade (Database db, int oldVersion, int newVersion)"

.PP
在文件 DaoMaster\&.java 第 113 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
