.TH "com.angelmsger.cslaboratory.forum.ForumContent" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.forum.ForumContent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final List< \fBForumTopicItem\fP > \fBITEMS\fP = new ArrayList<\fBForumTopicItem\fP>()"
.br
.in -1c
.SS "包函数"

.in +1c
.ti -1c
.RI "synchronized int \fBupdate\fP (\fBForumContent\fP forumContent, boolean pushToBottom)"
.br
.in -1c
.SH "详细描述"
.PP 
为用户接口提供内容的帮助类。 TODO: 根据需要替换为具体实现。 
.PP
在文件 ForumContent\&.java 第 12 行定义\&.
.SH "成员函数说明"
.PP 
.SS "synchronized int com\&.angelmsger\&.cslaboratory\&.forum\&.ForumContent\&.update (\fBForumContent\fP forumContent, boolean pushToBottom)\fC [package]\fP"

.PP
在文件 ForumContent\&.java 第 19 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final List<\fBForumTopicItem\fP> com\&.angelmsger\&.cslaboratory\&.forum\&.ForumContent\&.ITEMS = new ArrayList<\fBForumTopicItem\fP>()"
数据项实例数组。 
.PP
在文件 ForumContent\&.java 第 17 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
