.TH "com.angelmsger.cslaboratory.login.User.Extra" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.login.User.Extra \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBExtra\fP ()"
.br
.ti -1c
.RI "\fBExtra\fP (int \fBsex\fP, int \fBtopicCount\fP, int \fBreplyCount\fP, int \fBfollowerCount\fP, int \fBgoodTopicCount\fP, int \fBfavUser\fP, int \fBfavTag\fP, int \fBfavTopic\fP)"
.br
.ti -1c
.RI "int \fBgetSex\fP ()"
.br
.ti -1c
.RI "void \fBsetSex\fP (int \fBsex\fP)"
.br
.ti -1c
.RI "int \fBgetTopicCount\fP ()"
.br
.ti -1c
.RI "void \fBsetTopicCount\fP (int \fBtopicCount\fP)"
.br
.ti -1c
.RI "int \fBgetReplyCount\fP ()"
.br
.ti -1c
.RI "void \fBsetReplyCount\fP (int \fBreplyCount\fP)"
.br
.ti -1c
.RI "int \fBgetFollowerCount\fP ()"
.br
.ti -1c
.RI "void \fBsetFollowerCount\fP (int \fBfollowerCount\fP)"
.br
.ti -1c
.RI "int \fBgetGoodTopicCount\fP ()"
.br
.ti -1c
.RI "void \fBsetGoodTopicCount\fP (int \fBgoodTopicCount\fP)"
.br
.ti -1c
.RI "int \fBgetFavUser\fP ()"
.br
.ti -1c
.RI "void \fBsetFavUser\fP (int \fBfavUser\fP)"
.br
.ti -1c
.RI "int \fBgetFavTag\fP ()"
.br
.ti -1c
.RI "void \fBsetFavTag\fP (int \fBfavTag\fP)"
.br
.ti -1c
.RI "int \fBgetFavTopic\fP ()"
.br
.ti -1c
.RI "void \fBsetFavTopic\fP (int \fBfavTopic\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "int \fBsex\fP"
.br
.ti -1c
.RI "int \fBtopicCount\fP"
.br
.ti -1c
.RI "int \fBreplyCount\fP"
.br
.ti -1c
.RI "int \fBfollowerCount\fP"
.br
.ti -1c
.RI "int \fBgoodTopicCount\fP"
.br
.ti -1c
.RI "int \fBfavUser\fP"
.br
.ti -1c
.RI "int \fBfavTag\fP"
.br
.ti -1c
.RI "int \fBfavTopic\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 User\&.java 第 80 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.Extra ()"

.PP
在文件 User\&.java 第 90 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.Extra (int sex, int topicCount, int replyCount, int followerCount, int goodTopicCount, int favUser, int favTag, int favTopic)"

.PP
在文件 User\&.java 第 93 行定义\&.
.SH "成员函数说明"
.PP 
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getFavTag ()"

.PP
在文件 User\&.java 第 153 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getFavTopic ()"

.PP
在文件 User\&.java 第 161 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getFavUser ()"

.PP
在文件 User\&.java 第 145 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getFollowerCount ()"

.PP
在文件 User\&.java 第 129 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getGoodTopicCount ()"

.PP
在文件 User\&.java 第 137 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getReplyCount ()"

.PP
在文件 User\&.java 第 121 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getSex ()"

.PP
在文件 User\&.java 第 105 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.getTopicCount ()"

.PP
在文件 User\&.java 第 113 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setFavTag (int favTag)"

.PP
在文件 User\&.java 第 157 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setFavTopic (int favTopic)"

.PP
在文件 User\&.java 第 165 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setFavUser (int favUser)"

.PP
在文件 User\&.java 第 149 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setFollowerCount (int followerCount)"

.PP
在文件 User\&.java 第 133 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setGoodTopicCount (int goodTopicCount)"

.PP
在文件 User\&.java 第 141 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setReplyCount (int replyCount)"

.PP
在文件 User\&.java 第 125 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setSex (int sex)"

.PP
在文件 User\&.java 第 109 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.setTopicCount (int topicCount)"

.PP
在文件 User\&.java 第 117 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.favTag\fC [private]\fP"

.PP
在文件 User\&.java 第 87 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.favTopic\fC [private]\fP"

.PP
在文件 User\&.java 第 88 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.favUser\fC [private]\fP"

.PP
在文件 User\&.java 第 86 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.followerCount\fC [private]\fP"

.PP
在文件 User\&.java 第 84 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.goodTopicCount\fC [private]\fP"

.PP
在文件 User\&.java 第 85 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.replyCount\fC [private]\fP"

.PP
在文件 User\&.java 第 83 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.sex\fC [private]\fP"

.PP
在文件 User\&.java 第 81 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.login\&.User\&.Extra\&.topicCount\fC [private]\fP"

.PP
在文件 User\&.java 第 82 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
