.TH "com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.ADPagerAdapter" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.ADPagerAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 PagerAdapter \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBADPagerAdapter\fP ()"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "boolean \fBisViewFromObject\fP (View view, Object object)"
.br
.ti -1c
.RI "Object \fBinstantiateItem\fP (ViewGroup container, int position)"
.br
.ti -1c
.RI "void \fBdestroyItem\fP (ViewGroup container, int position, Object object)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "final List< ImageView > \fBmADViews\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 QualityRecyclerViewAdapter\&.java 第 212 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADPagerAdapter\&.ADPagerAdapter ()"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 215 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADPagerAdapter\&.destroyItem (ViewGroup container, int position, Object object)"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 259 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADPagerAdapter\&.getCount ()"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 238 行定义\&.
.SS "Object com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADPagerAdapter\&.instantiateItem (ViewGroup container, int position)"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 248 行定义\&.
.SS "boolean com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADPagerAdapter\&.isViewFromObject (View view, Object object)"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 243 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final List<ImageView> com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.ADPagerAdapter\&.mADViews\fC [private]\fP"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 213 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
