.TH "com.angelmsger.cslaboratory.course.subclass.SubclassRecyclerViewAdapter.CourseClassViewHolder" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.course.subclass.SubclassRecyclerViewAdapter.CourseClassViewHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 ViewHolder \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBCourseClassViewHolder\fP (View view)"
.br
.ti -1c
.RI "void \fBbind\fP (final \fBCourseSubclassItem\fP item)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final View \fBmView\fP"
.br
.ti -1c
.RI "final CircleImageView \fBmImage\fP"
.br
.ti -1c
.RI "final TextView \fBmTitle\fP"
.br
.ti -1c
.RI "\fBCourseSubclassItem\fP \fBmItem\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 SubclassRecyclerViewAdapter\&.java 第 56 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.SubclassRecyclerViewAdapter\&.CourseClassViewHolder\&.CourseClassViewHolder (View view)"

.PP
在文件 SubclassRecyclerViewAdapter\&.java 第 62 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.SubclassRecyclerViewAdapter\&.CourseClassViewHolder\&.bind (final \fBCourseSubclassItem\fP item)"

.PP
在文件 SubclassRecyclerViewAdapter\&.java 第 69 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final CircleImageView com\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.SubclassRecyclerViewAdapter\&.CourseClassViewHolder\&.mImage"

.PP
在文件 SubclassRecyclerViewAdapter\&.java 第 58 行定义\&.
.SS "\fBCourseSubclassItem\fP com\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.SubclassRecyclerViewAdapter\&.CourseClassViewHolder\&.mItem"

.PP
在文件 SubclassRecyclerViewAdapter\&.java 第 60 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.SubclassRecyclerViewAdapter\&.CourseClassViewHolder\&.mTitle"

.PP
在文件 SubclassRecyclerViewAdapter\&.java 第 59 行定义\&.
.SS "final View com\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.SubclassRecyclerViewAdapter\&.CourseClassViewHolder\&.mView"

.PP
在文件 SubclassRecyclerViewAdapter\&.java 第 57 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
