.TH "com.angelmsger.cslaboratory.course.subclass.SubclassContent" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.course.subclass.SubclassContent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final List< \fBCourseSubclassItem\fP > \fBITEMS\fP = new ArrayList<>()"
.br
.in -1c
.SH "详细描述"
.PP 
为用户接口提供内容的帮助类。 TODO: 根据需要替换为具体实现。 
.PP
在文件 SubclassContent\&.java 第 12 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final List<\fBCourseSubclassItem\fP> com\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.SubclassContent\&.ITEMS = new ArrayList<>()"
数据项实例数组。 
.PP
在文件 SubclassContent\&.java 第 16 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
