.TH "com.angelmsger.cslaboratory.dao.QualityArticleItemDao" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.dao.QualityArticleItemDao \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 AbstractDao< QualityArticleItem, Long > \&.
.SS "类"

.in +1c
.ti -1c
.RI "class \fBProperties\fP"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBQualityArticleItemDao\fP (DaoConfig config)"
.br
.ti -1c
.RI "\fBQualityArticleItemDao\fP (DaoConfig config, \fBDaoSession\fP daoSession)"
.br
.ti -1c
.RI "Long \fBreadKey\fP (Cursor cursor, int offset)"
.br
.ti -1c
.RI "\fBQualityArticleItem\fP \fBreadEntity\fP (Cursor cursor, int offset)"
.br
.ti -1c
.RI "void \fBreadEntity\fP (Cursor cursor, \fBQualityArticleItem\fP entity, int offset)"
.br
.ti -1c
.RI "Long \fBgetKey\fP (\fBQualityArticleItem\fP entity)"
.br
.ti -1c
.RI "boolean \fBhasKey\fP (\fBQualityArticleItem\fP entity)"
.br
.in -1c
.SS "静态 Public 成员函数"

.in +1c
.ti -1c
.RI "static void \fBcreateTable\fP (Database db, boolean ifNotExists)"
.br
.ti -1c
.RI "static void \fBdropTable\fP (Database db, boolean ifExists)"
.br
.in -1c
.SS "静态 Public 属性"

.in +1c
.ti -1c
.RI "static final String \fBTABLENAME\fP = 'quality_articles'"
.br
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "final void \fBbindValues\fP (DatabaseStatement stmt, \fBQualityArticleItem\fP entity)"
.br
.ti -1c
.RI "final void \fBbindValues\fP (SQLiteStatement stmt, \fBQualityArticleItem\fP entity)"
.br
.ti -1c
.RI "final Long \fBupdateKeyAfterInsert\fP (\fBQualityArticleItem\fP entity, long rowId)"
.br
.ti -1c
.RI "final boolean \fBisEntityUpdateable\fP ()"
.br
.in -1c
.SH "详细描述"
.PP 
DAO for table 'quality_articles'\&. 
.PP
在文件 QualityArticleItemDao\&.java 第 18 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.QualityArticleItemDao (DaoConfig config)"

.PP
在文件 QualityArticleItemDao\&.java 第 38 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.QualityArticleItemDao (DaoConfig config, \fBDaoSession\fP daoSession)"

.PP
在文件 QualityArticleItemDao\&.java 第 42 行定义\&.
.SH "成员函数说明"
.PP 
.SS "final void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.bindValues (DatabaseStatement stmt, \fBQualityArticleItem\fP entity)\fC [protected]\fP"

.PP
在文件 QualityArticleItemDao\&.java 第 72 行定义\&.
.SS "final void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.bindValues (SQLiteStatement stmt, \fBQualityArticleItem\fP entity)\fC [protected]\fP"

.PP
在文件 QualityArticleItemDao\&.java 第 101 行定义\&.
.SS "static void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.createTable (Database db, boolean ifNotExists)\fC [static]\fP"
Creates the underlying database table\&. 
.PP
在文件 QualityArticleItemDao\&.java 第 47 行定义\&.
.SS "static void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.dropTable (Database db, boolean ifExists)\fC [static]\fP"
Drops the underlying database table\&. 
.PP
在文件 QualityArticleItemDao\&.java 第 66 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.getKey (\fBQualityArticleItem\fP entity)"

.PP
在文件 QualityArticleItemDao\&.java 第 168 行定义\&.
.SS "boolean com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.hasKey (\fBQualityArticleItem\fP entity)"

.PP
在文件 QualityArticleItemDao\&.java 第 177 行定义\&.
.SS "final boolean com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.isEntityUpdateable ()\fC [protected]\fP"

.PP
在文件 QualityArticleItemDao\&.java 第 182 行定义\&.
.SS "\fBQualityArticleItem\fP com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.readEntity (Cursor cursor, int offset)"

.PP
在文件 QualityArticleItemDao\&.java 第 135 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.readEntity (Cursor cursor, \fBQualityArticleItem\fP entity, int offset)"

.PP
在文件 QualityArticleItemDao\&.java 第 150 行定义\&.
.SS "Long com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.readKey (Cursor cursor, int offset)"

.PP
在文件 QualityArticleItemDao\&.java 第 130 行定义\&.
.SS "final Long com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.updateKeyAfterInsert (\fBQualityArticleItem\fP entity, long rowId)\fC [protected]\fP"

.PP
在文件 QualityArticleItemDao\&.java 第 162 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final String com\&.angelmsger\&.cslaboratory\&.dao\&.QualityArticleItemDao\&.TABLENAME = 'quality_articles'\fC [static]\fP"

.PP
在文件 QualityArticleItemDao\&.java 第 20 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
