.TH "com.angelmsger.cslaboratory.login.User" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.login.User \- 
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "class \fBBase\fP"
.br
.ti -1c
.RI "class \fBExtra\fP"
.br
.in -1c
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBUser\fP ()"
.br
.ti -1c
.RI "\fBUser\fP (\fBBase\fP \fBbase\fP, \fBExtra\fP \fBextra\fP)"
.br
.ti -1c
.RI "\fBBase\fP \fBgetBase\fP ()"
.br
.ti -1c
.RI "void \fBsetBase\fP (\fBBase\fP \fBbase\fP)"
.br
.ti -1c
.RI "\fBExtra\fP \fBgetExtra\fP ()"
.br
.ti -1c
.RI "void \fBsetExtra\fP (\fBExtra\fP \fBextra\fP)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "\fBBase\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBExtra\fP \fBextra\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 User\&.java 第 3 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.User\&.User ()"

.PP
在文件 User\&.java 第 7 行定义\&.
.SS "com\&.angelmsger\&.cslaboratory\&.login\&.User\&.User (\fBBase\fP base, \fBExtra\fP extra)"

.PP
在文件 User\&.java 第 10 行定义\&.
.SH "成员函数说明"
.PP 
.SS "\fBBase\fP com\&.angelmsger\&.cslaboratory\&.login\&.User\&.getBase ()"

.PP
在文件 User\&.java 第 15 行定义\&.
.SS "\fBExtra\fP com\&.angelmsger\&.cslaboratory\&.login\&.User\&.getExtra ()"

.PP
在文件 User\&.java 第 23 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.setBase (\fBBase\fP base)"

.PP
在文件 User\&.java 第 19 行定义\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.login\&.User\&.setExtra (\fBExtra\fP extra)"

.PP
在文件 User\&.java 第 27 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "\fBBase\fP com\&.angelmsger\&.cslaboratory\&.login\&.User\&.base\fC [private]\fP"

.PP
在文件 User\&.java 第 4 行定义\&.
.SS "\fBExtra\fP com\&.angelmsger\&.cslaboratory\&.login\&.User\&.extra\fC [private]\fP"

.PP
在文件 User\&.java 第 5 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
