.TH "com.angelmsger.cslaboratory.source.UnrealDataSource" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.source.UnrealDataSource \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "Login\&.Response \fBattemptLogin\fP (Login\&.Request request)"
.br
.ti -1c
.RI "\fBCourseContent\fP \fBgetCourseContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBDailyContent\fP \fBgetDailyContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBForumContent\fP \fBgetForumContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBQualityContent\fP \fBgetQualityContent\fP (final int offset, final int limit)"
.br
.ti -1c
.RI "\fBTopologyContent\fP \fBgetTopologyContent\fP (final int offset, final int limit)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "int [] \fBmRequestsCount\fP = { 0, 0, 0, 0, 0 }"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 UnrealDataSource\&.java 第 24 行定义\&.
.SH "成员函数说明"
.PP 
.SS "Login\&.Response com\&.angelmsger\&.cslaboratory\&.source\&.UnrealDataSource\&.attemptLogin (Login\&.Request request)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 UnrealDataSource\&.java 第 28 行定义\&.
.SS "\fBCourseContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.UnrealDataSource\&.getCourseContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 UnrealDataSource\&.java 第 50 行定义\&.
.SS "\fBDailyContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.UnrealDataSource\&.getDailyContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 UnrealDataSource\&.java 第 90 行定义\&.
.SS "\fBForumContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.UnrealDataSource\&.getForumContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 UnrealDataSource\&.java 第 95 行定义\&.
.SS "\fBQualityContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.UnrealDataSource\&.getQualityContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 UnrealDataSource\&.java 第 126 行定义\&.
.SS "\fBTopologyContent\fP com\&.angelmsger\&.cslaboratory\&.source\&.UnrealDataSource\&.getTopologyContent (final int offset, final int limit)"

.PP
实现了 \fBcom\&.angelmsger\&.cslaboratory\&.source\&.DataSource\fP\&.
.PP
在文件 UnrealDataSource\&.java 第 173 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "int [] com\&.angelmsger\&.cslaboratory\&.source\&.UnrealDataSource\&.mRequestsCount = { 0, 0, 0, 0, 0 }\fC [private]\fP"

.PP
在文件 UnrealDataSource\&.java 第 25 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
