.TH "com.angelmsger.cslaboratory.MainActivity.SectionsPagerAdapter" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.MainActivity.SectionsPagerAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 FragmentPagerAdapter \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBSectionsPagerAdapter\fP (FragmentManager fm)"
.br
.ti -1c
.RI "Fragment \fBgetItem\fP (int position)"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "CharSequence \fBgetPageTitle\fP (int position)"
.br
.ti -1c
.RI "void \fBdestroyItem\fP (ViewGroup container, int position, Object object)"
.br
.in -1c
.SH "详细描述"
.PP 
\fBandroid\&.support\&.v4\&.view\&.PagerAdapter\fP 将为每一页提供 fragments。 使用一个\fBFragmentPagerAdapter\fP 子类，将在内存中保持每一个载入的 fragment。 如果这使得内存占用过高，则它可以被替换为 \fBandroid\&.support\&.v4\&.app\&.FragmentStatePagerAdapter\fP\&. 
.PP
在文件 MainActivity\&.java 第 407 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.MainActivity\&.SectionsPagerAdapter\&.SectionsPagerAdapter (FragmentManager fm)"

.PP
在文件 MainActivity\&.java 第 409 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.MainActivity\&.SectionsPagerAdapter\&.destroyItem (ViewGroup container, int position, Object object)"

.PP
在文件 MainActivity\&.java 第 431 行定义\&.
.SS "int com\&.angelmsger\&.cslaboratory\&.MainActivity\&.SectionsPagerAdapter\&.getCount ()"

.PP
在文件 MainActivity\&.java 第 420 行定义\&.
.SS "Fragment com\&.angelmsger\&.cslaboratory\&.MainActivity\&.SectionsPagerAdapter\&.getItem (int position)"

.PP
在文件 MainActivity\&.java 第 414 行定义\&.
.SS "CharSequence com\&.angelmsger\&.cslaboratory\&.MainActivity\&.SectionsPagerAdapter\&.getPageTitle (int position)"

.PP
在文件 MainActivity\&.java 第 426 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
