.TH "com.angelmsger.cslaboratory.course.CourseFragment.OnListFragmentInteractionListener" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.course.CourseFragment.OnListFragmentInteractionListener \- 
.SH SYNOPSIS
.br
.PP
.PP
被 \fBcom\&.angelmsger\&.cslaboratory\&.MainActivity\fP 继承\&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "void \fBonCourseListScroll\fP ()"
.br
.ti -1c
.RI "void \fBonCourseListUpdate\fP (final int updateCount)"
.br
.ti -1c
.RI "void \fBonCourseCategoryItemClick\fP (\fBCourseSubclassItem\fP courseSubclassItem)"
.br
.ti -1c
.RI "void \fBonCourseItemClick\fP (\fBCourseCourseItem\fP courseCourseItem)"
.br
.in -1c
.SH "详细描述"
.PP 
包含此 fragment 的 activity 必须实现此接口来允许一此 fragment 和此 activity 及此 activity 中 包含的其他 fragment 进行通信。 查看 Android 训练课程 \fCCommunicating with Other Fragments\fP 以获取更多信息。 
.PP
在文件 CourseFragment\&.java 第 173 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.CourseFragment\&.OnListFragmentInteractionListener\&.onCourseCategoryItemClick (\fBCourseSubclassItem\fP courseSubclassItem)"

.PP
在 \fBcom\&.angelmsger\&.cslaboratory\&.MainActivity\fP 内被实现\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.CourseFragment\&.OnListFragmentInteractionListener\&.onCourseItemClick (\fBCourseCourseItem\fP courseCourseItem)"

.PP
在 \fBcom\&.angelmsger\&.cslaboratory\&.MainActivity\fP 内被实现\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.CourseFragment\&.OnListFragmentInteractionListener\&.onCourseListScroll ()"

.PP
在 \fBcom\&.angelmsger\&.cslaboratory\&.MainActivity\fP 内被实现\&.
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.CourseFragment\&.OnListFragmentInteractionListener\&.onCourseListUpdate (final int updateCount)"

.PP
在 \fBcom\&.angelmsger\&.cslaboratory\&.MainActivity\fP 内被实现\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
