.TH "com.angelmsger.cslaboratory.topology.TopologyContent" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.topology.TopologyContent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final List< \fBTopologyFieldItem\fP > \fBITEMS\fP = new ArrayList<\fBTopologyFieldItem\fP>()"
.br
.in -1c
.SS "包函数"

.in +1c
.ti -1c
.RI "synchronized int \fBupdate\fP (\fBTopologyContent\fP topologyContent, boolean pushToBottom)"
.br
.in -1c
.SH "详细描述"
.PP 
为用户接口提供内容的帮助类。 TODO: 根据需要替换为具体实现。 
.PP
在文件 TopologyContent\&.java 第 12 行定义\&.
.SH "成员函数说明"
.PP 
.SS "synchronized int com\&.angelmsger\&.cslaboratory\&.topology\&.TopologyContent\&.update (\fBTopologyContent\fP topologyContent, boolean pushToBottom)\fC [package]\fP"

.PP
在文件 TopologyContent\&.java 第 18 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final List<\fBTopologyFieldItem\fP> com\&.angelmsger\&.cslaboratory\&.topology\&.TopologyContent\&.ITEMS = new ArrayList<\fBTopologyFieldItem\fP>()"
数据项实例数组。 
.PP
在文件 TopologyContent\&.java 第 16 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
