.TH "com.angelmsger.cslaboratory.ProprietaryReceiver" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.ProprietaryReceiver \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 BroadcastReceiver \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBProprietaryReceiver\fP ()"
.br
.ti -1c
.RI "void \fBonReceive\fP (Context context, Intent intent)"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 ProprietaryReceiver\&.java 第 7 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.ProprietaryReceiver\&.ProprietaryReceiver ()"

.PP
在文件 ProprietaryReceiver\&.java 第 8 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.ProprietaryReceiver\&.onReceive (Context context, Intent intent)"

.PP
在文件 ProprietaryReceiver\&.java 第 12 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
