.TH "com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.CourseViewHolder" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.CourseViewHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 ViewHolder \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBCourseViewHolder\fP (View view)"
.br
.ti -1c
.RI "void \fBbind\fP (final \fBCourseCourseItem\fP courseCourseItem)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final View \fBmView\fP"
.br
.ti -1c
.RI "final ImageView \fBmImage\fP"
.br
.ti -1c
.RI "final TextView \fBmTitle\fP"
.br
.ti -1c
.RI "final TextView \fBmLearnerCount\fP"
.br
.ti -1c
.RI "\fBCourseCourseItem\fP \fBmItem\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 CourseRecyclerViewAdapter\&.java 第 112 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseViewHolder\&.CourseViewHolder (View view)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 119 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseViewHolder\&.bind (final \fBCourseCourseItem\fP courseCourseItem)"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 127 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final ImageView com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseViewHolder\&.mImage"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 114 行定义\&.
.SS "\fBCourseCourseItem\fP com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseViewHolder\&.mItem"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 117 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseViewHolder\&.mLearnerCount"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 116 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseViewHolder\&.mTitle"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 115 行定义\&.
.SS "final View com\&.angelmsger\&.cslaboratory\&.course\&.CourseRecyclerViewAdapter\&.CourseViewHolder\&.mView"

.PP
在文件 CourseRecyclerViewAdapter\&.java 第 113 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
