.TH "com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder \- 
.SH SYNOPSIS
.br
.PP
.PP
继承自 ViewHolder \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBQualityViewHolder\fP (View view)"
.br
.ti -1c
.RI "void \fBbind\fP (final \fBQualityArticleItem\fP item)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "final View \fBmView\fP"
.br
.ti -1c
.RI "final TextView \fBmClass\fP"
.br
.ti -1c
.RI "final ImageView \fBmImage\fP"
.br
.ti -1c
.RI "final TextView \fBmTitle\fP"
.br
.ti -1c
.RI "final TextView \fBmContent\fP"
.br
.ti -1c
.RI "final TextView \fBmAttitude\fP"
.br
.ti -1c
.RI "\fBQualityArticleItem\fP \fBmItem\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 QualityRecyclerViewAdapter\&.java 第 174 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.QualityViewHolder (View view)"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 183 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.bind (final \fBQualityArticleItem\fP item)"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 193 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.mAttitude"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 180 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.mClass"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 176 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.mContent"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 179 行定义\&.
.SS "final ImageView com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.mImage"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 177 行定义\&.
.SS "\fBQualityArticleItem\fP com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.mItem"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 181 行定义\&.
.SS "final TextView com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.mTitle"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 178 行定义\&.
.SS "final View com\&.angelmsger\&.cslaboratory\&.quality\&.QualityRecyclerViewAdapter\&.QualityViewHolder\&.mView"

.PP
在文件 QualityRecyclerViewAdapter\&.java 第 175 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
