.TH "D:/Workspace/AndroidStudio/CSLaboratory/app/src/main/java/com/angelmsger/cslaboratory/course/subclass/CourseSubclassItem.java" 3 "2016年 十二月 27日 星期二" "Version 0.1.0" "猫爪实验室" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/AndroidStudio/CSLaboratory/app/src/main/java/com/angelmsger/cslaboratory/course/subclass/CourseSubclassItem.java \- 
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "class \fBcom\&.angelmsger\&.cslaboratory\&.course\&.subclass\&.CourseSubclassItem\fP"
.br
.in -1c
.SS "包"

.in +1c
.ti -1c
.RI "package \fBcom\&.angelmsger\&.cslaboratory\&.course\&.subclass\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 猫爪实验室 的 源代码自动生成\&.
