package com.angelmsger.cslaboratory.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.angelmsger.cslaboratory.daily.article.DailyArticleItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "daily_articles".
*/
public class DailyArticleItemDao extends AbstractDao<DailyArticleItem, Long> {

    public static final String TABLENAME = "daily_articles";

    /**
     * Properties of entity DailyArticleItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BannerURI = new Property(1, String.class, "bannerURI", false, "BANNER_URI");
        public final static Property ImageURI = new Property(2, String.class, "imageURI", false, "IMAGE_URI");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property PostTime = new Property(5, String.class, "postTime", false, "POST_TIME");
    }


    public DailyArticleItemDao(DaoConfig config) {
        super(config);
    }
    
    public DailyArticleItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"daily_articles\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BANNER_URI\" TEXT NOT NULL ," + // 1: bannerURI
                "\"IMAGE_URI\" TEXT NOT NULL ," + // 2: imageURI
                "\"TITLE\" TEXT NOT NULL ," + // 3: title
                "\"CONTENT\" TEXT," + // 4: content
                "\"POST_TIME\" TEXT);"); // 5: postTime
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "TitlePostTimeIndex ON daily_articles" +
                " (\"TITLE\" ASC,\"POST_TIME\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"daily_articles\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DailyArticleItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBannerURI());
        stmt.bindString(3, entity.getImageURI());
        stmt.bindString(4, entity.getTitle());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String postTime = entity.getPostTime();
        if (postTime != null) {
            stmt.bindString(6, postTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DailyArticleItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBannerURI());
        stmt.bindString(3, entity.getImageURI());
        stmt.bindString(4, entity.getTitle());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String postTime = entity.getPostTime();
        if (postTime != null) {
            stmt.bindString(6, postTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DailyArticleItem readEntity(Cursor cursor, int offset) {
        DailyArticleItem entity = new DailyArticleItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // bannerURI
            cursor.getString(offset + 2), // imageURI
            cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // content
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // postTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DailyArticleItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBannerURI(cursor.getString(offset + 1));
        entity.setImageURI(cursor.getString(offset + 2));
        entity.setTitle(cursor.getString(offset + 3));
        entity.setContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPostTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DailyArticleItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DailyArticleItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DailyArticleItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
