package com.angelmsger.cslaboratory.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.angelmsger.cslaboratory.course.course.CourseCourseItem;
import com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem;
import com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem;
import com.angelmsger.cslaboratory.daily.article.DailyArticleItem;
import com.angelmsger.cslaboratory.forum.topic.ForumTopicItem;
import com.angelmsger.cslaboratory.quality.ad.QualityADItem;
import com.angelmsger.cslaboratory.quality.article.QualityArticleItem;
import com.angelmsger.cslaboratory.quality.category.QualityCategoryItem;
import com.angelmsger.cslaboratory.topology.field.TopologyFieldItem;

import com.angelmsger.cslaboratory.dao.CourseCourseItemDao;
import com.angelmsger.cslaboratory.dao.CourseCategoryItemDao;
import com.angelmsger.cslaboratory.dao.CourseSubclassItemDao;
import com.angelmsger.cslaboratory.dao.DailyArticleItemDao;
import com.angelmsger.cslaboratory.dao.ForumTopicItemDao;
import com.angelmsger.cslaboratory.dao.QualityADItemDao;
import com.angelmsger.cslaboratory.dao.QualityArticleItemDao;
import com.angelmsger.cslaboratory.dao.QualityCategoryItemDao;
import com.angelmsger.cslaboratory.dao.TopologyFieldItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseCourseItemDaoConfig;
    private final DaoConfig courseCategoryItemDaoConfig;
    private final DaoConfig courseSubclassItemDaoConfig;
    private final DaoConfig dailyArticleItemDaoConfig;
    private final DaoConfig forumTopicItemDaoConfig;
    private final DaoConfig qualityADItemDaoConfig;
    private final DaoConfig qualityArticleItemDaoConfig;
    private final DaoConfig qualityCategoryItemDaoConfig;
    private final DaoConfig topologyFieldItemDaoConfig;

    private final CourseCourseItemDao courseCourseItemDao;
    private final CourseCategoryItemDao courseCategoryItemDao;
    private final CourseSubclassItemDao courseSubclassItemDao;
    private final DailyArticleItemDao dailyArticleItemDao;
    private final ForumTopicItemDao forumTopicItemDao;
    private final QualityADItemDao qualityADItemDao;
    private final QualityArticleItemDao qualityArticleItemDao;
    private final QualityCategoryItemDao qualityCategoryItemDao;
    private final TopologyFieldItemDao topologyFieldItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseCourseItemDaoConfig = daoConfigMap.get(CourseCourseItemDao.class).clone();
        courseCourseItemDaoConfig.initIdentityScope(type);

        courseCategoryItemDaoConfig = daoConfigMap.get(CourseCategoryItemDao.class).clone();
        courseCategoryItemDaoConfig.initIdentityScope(type);

        courseSubclassItemDaoConfig = daoConfigMap.get(CourseSubclassItemDao.class).clone();
        courseSubclassItemDaoConfig.initIdentityScope(type);

        dailyArticleItemDaoConfig = daoConfigMap.get(DailyArticleItemDao.class).clone();
        dailyArticleItemDaoConfig.initIdentityScope(type);

        forumTopicItemDaoConfig = daoConfigMap.get(ForumTopicItemDao.class).clone();
        forumTopicItemDaoConfig.initIdentityScope(type);

        qualityADItemDaoConfig = daoConfigMap.get(QualityADItemDao.class).clone();
        qualityADItemDaoConfig.initIdentityScope(type);

        qualityArticleItemDaoConfig = daoConfigMap.get(QualityArticleItemDao.class).clone();
        qualityArticleItemDaoConfig.initIdentityScope(type);

        qualityCategoryItemDaoConfig = daoConfigMap.get(QualityCategoryItemDao.class).clone();
        qualityCategoryItemDaoConfig.initIdentityScope(type);

        topologyFieldItemDaoConfig = daoConfigMap.get(TopologyFieldItemDao.class).clone();
        topologyFieldItemDaoConfig.initIdentityScope(type);

        courseCourseItemDao = new CourseCourseItemDao(courseCourseItemDaoConfig, this);
        courseCategoryItemDao = new CourseCategoryItemDao(courseCategoryItemDaoConfig, this);
        courseSubclassItemDao = new CourseSubclassItemDao(courseSubclassItemDaoConfig, this);
        dailyArticleItemDao = new DailyArticleItemDao(dailyArticleItemDaoConfig, this);
        forumTopicItemDao = new ForumTopicItemDao(forumTopicItemDaoConfig, this);
        qualityADItemDao = new QualityADItemDao(qualityADItemDaoConfig, this);
        qualityArticleItemDao = new QualityArticleItemDao(qualityArticleItemDaoConfig, this);
        qualityCategoryItemDao = new QualityCategoryItemDao(qualityCategoryItemDaoConfig, this);
        topologyFieldItemDao = new TopologyFieldItemDao(topologyFieldItemDaoConfig, this);

        registerDao(CourseCourseItem.class, courseCourseItemDao);
        registerDao(CourseCategoryItem.class, courseCategoryItemDao);
        registerDao(CourseSubclassItem.class, courseSubclassItemDao);
        registerDao(DailyArticleItem.class, dailyArticleItemDao);
        registerDao(ForumTopicItem.class, forumTopicItemDao);
        registerDao(QualityADItem.class, qualityADItemDao);
        registerDao(QualityArticleItem.class, qualityArticleItemDao);
        registerDao(QualityCategoryItem.class, qualityCategoryItemDao);
        registerDao(TopologyFieldItem.class, topologyFieldItemDao);
    }
    
    public void clear() {
        courseCourseItemDaoConfig.clearIdentityScope();
        courseCategoryItemDaoConfig.clearIdentityScope();
        courseSubclassItemDaoConfig.clearIdentityScope();
        dailyArticleItemDaoConfig.clearIdentityScope();
        forumTopicItemDaoConfig.clearIdentityScope();
        qualityADItemDaoConfig.clearIdentityScope();
        qualityArticleItemDaoConfig.clearIdentityScope();
        qualityCategoryItemDaoConfig.clearIdentityScope();
        topologyFieldItemDaoConfig.clearIdentityScope();
    }

    public CourseCourseItemDao getCourseCourseItemDao() {
        return courseCourseItemDao;
    }

    public CourseCategoryItemDao getCourseCategoryItemDao() {
        return courseCategoryItemDao;
    }

    public CourseSubclassItemDao getCourseSubclassItemDao() {
        return courseSubclassItemDao;
    }

    public DailyArticleItemDao getDailyArticleItemDao() {
        return dailyArticleItemDao;
    }

    public ForumTopicItemDao getForumTopicItemDao() {
        return forumTopicItemDao;
    }

    public QualityADItemDao getQualityADItemDao() {
        return qualityADItemDao;
    }

    public QualityArticleItemDao getQualityArticleItemDao() {
        return qualityArticleItemDao;
    }

    public QualityCategoryItemDao getQualityCategoryItemDao() {
        return qualityCategoryItemDao;
    }

    public TopologyFieldItemDao getTopologyFieldItemDao() {
        return topologyFieldItemDao;
    }

}
