package com.angelmsger.cslaboratory.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.angelmsger.cslaboratory.forum.topic.ForumTopicItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "forum_topics".
*/
public class ForumTopicItemDao extends AbstractDao<ForumTopicItem, Long> {

    public static final String TABLENAME = "forum_topics";

    /**
     * Properties of entity ForumTopicItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AvatarURI = new Property(1, String.class, "avatarURI", false, "AVATAR_URI");
        public final static Property Nickname = new Property(2, String.class, "nickname", false, "NICKNAME");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
    }


    public ForumTopicItemDao(DaoConfig config) {
        super(config);
    }
    
    public ForumTopicItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"forum_topics\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"AVATAR_URI\" TEXT," + // 1: avatarURI
                "\"NICKNAME\" TEXT NOT NULL ," + // 2: nickname
                "\"TITLE\" TEXT NOT NULL ," + // 3: title
                "\"CONTENT\" TEXT NOT NULL );"); // 4: content
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "NicknameIndex ON forum_topics" +
                " (\"NICKNAME\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"forum_topics\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ForumTopicItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String avatarURI = entity.getAvatarURI();
        if (avatarURI != null) {
            stmt.bindString(2, avatarURI);
        }
        stmt.bindString(3, entity.getNickname());
        stmt.bindString(4, entity.getTitle());
        stmt.bindString(5, entity.getContent());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ForumTopicItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String avatarURI = entity.getAvatarURI();
        if (avatarURI != null) {
            stmt.bindString(2, avatarURI);
        }
        stmt.bindString(3, entity.getNickname());
        stmt.bindString(4, entity.getTitle());
        stmt.bindString(5, entity.getContent());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ForumTopicItem readEntity(Cursor cursor, int offset) {
        ForumTopicItem entity = new ForumTopicItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // avatarURI
            cursor.getString(offset + 2), // nickname
            cursor.getString(offset + 3), // title
            cursor.getString(offset + 4) // content
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ForumTopicItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAvatarURI(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickname(cursor.getString(offset + 2));
        entity.setTitle(cursor.getString(offset + 3));
        entity.setContent(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ForumTopicItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ForumTopicItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ForumTopicItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
