package com.angelmsger.cslaboratory.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.angelmsger.cslaboratory.quality.article.QualityArticleItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "quality_articles".
*/
public class QualityArticleItemDao extends AbstractDao<QualityArticleItem, Long> {

    public static final String TABLENAME = "quality_articles";

    /**
     * Properties of entity QualityArticleItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Group = new Property(2, String.class, "group", false, "GROUP");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property ImageURI = new Property(4, String.class, "imageURI", false, "IMAGE_URI");
        public final static Property ActionURI = new Property(5, String.class, "actionURI", false, "ACTION_URI");
        public final static Property BangCount = new Property(6, int.class, "bangCount", false, "BANG_COUNT");
        public final static Property CommentCount = new Property(7, int.class, "commentCount", false, "COMMENT_COUNT");
    }


    public QualityArticleItemDao(DaoConfig config) {
        super(config);
    }
    
    public QualityArticleItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"quality_articles\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT NOT NULL UNIQUE ," + // 1: title
                "\"GROUP\" TEXT," + // 2: group
                "\"CONTENT\" TEXT NOT NULL ," + // 3: content
                "\"IMAGE_URI\" TEXT," + // 4: imageURI
                "\"ACTION_URI\" TEXT," + // 5: actionURI
                "\"BANG_COUNT\" INTEGER NOT NULL ," + // 6: bangCount
                "\"COMMENT_COUNT\" INTEGER NOT NULL );"); // 7: commentCount
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "BangCountIndex ON quality_articles" +
                " (\"TITLE\" ASC,\"BANG_COUNT\" DESC);");
        db.execSQL("CREATE INDEX " + constraint + "CommentCountIndex ON quality_articles" +
                " (\"TITLE\" ASC,\"COMMENT_COUNT\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"quality_articles\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, QualityArticleItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String group = entity.getGroup();
        if (group != null) {
            stmt.bindString(3, group);
        }
        stmt.bindString(4, entity.getContent());
 
        String imageURI = entity.getImageURI();
        if (imageURI != null) {
            stmt.bindString(5, imageURI);
        }
 
        String actionURI = entity.getActionURI();
        if (actionURI != null) {
            stmt.bindString(6, actionURI);
        }
        stmt.bindLong(7, entity.getBangCount());
        stmt.bindLong(8, entity.getCommentCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, QualityArticleItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String group = entity.getGroup();
        if (group != null) {
            stmt.bindString(3, group);
        }
        stmt.bindString(4, entity.getContent());
 
        String imageURI = entity.getImageURI();
        if (imageURI != null) {
            stmt.bindString(5, imageURI);
        }
 
        String actionURI = entity.getActionURI();
        if (actionURI != null) {
            stmt.bindString(6, actionURI);
        }
        stmt.bindLong(7, entity.getBangCount());
        stmt.bindLong(8, entity.getCommentCount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public QualityArticleItem readEntity(Cursor cursor, int offset) {
        QualityArticleItem entity = new QualityArticleItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // group
            cursor.getString(offset + 3), // content
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // imageURI
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // actionURI
            cursor.getInt(offset + 6), // bangCount
            cursor.getInt(offset + 7) // commentCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, QualityArticleItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setGroup(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setContent(cursor.getString(offset + 3));
        entity.setImageURI(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setActionURI(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBangCount(cursor.getInt(offset + 6));
        entity.setCommentCount(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(QualityArticleItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(QualityArticleItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(QualityArticleItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
