package com.angelmsger.cslaboratory.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.angelmsger.cslaboratory.topology.field.TopologyFieldItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "topology_fields".
*/
public class TopologyFieldItemDao extends AbstractDao<TopologyFieldItem, Long> {

    public static final String TABLENAME = "topology_fields";

    /**
     * Properties of entity TopologyFieldItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BackgroundURI = new Property(1, String.class, "backgroundURI", false, "BACKGROUND_URI");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property ImageURI = new Property(4, String.class, "imageURI", false, "IMAGE_URI");
    }


    public TopologyFieldItemDao(DaoConfig config) {
        super(config);
    }
    
    public TopologyFieldItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"topology_fields\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BACKGROUND_URI\" TEXT NOT NULL ," + // 1: backgroundURI
                "\"TITLE\" TEXT NOT NULL ," + // 2: title
                "\"CONTENT\" TEXT NOT NULL ," + // 3: content
                "\"IMAGE_URI\" TEXT NOT NULL );"); // 4: imageURI
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "TitleIndex ON topology_fields" +
                " (\"TITLE\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"topology_fields\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TopologyFieldItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBackgroundURI());
        stmt.bindString(3, entity.getTitle());
        stmt.bindString(4, entity.getContent());
        stmt.bindString(5, entity.getImageURI());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TopologyFieldItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBackgroundURI());
        stmt.bindString(3, entity.getTitle());
        stmt.bindString(4, entity.getContent());
        stmt.bindString(5, entity.getImageURI());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TopologyFieldItem readEntity(Cursor cursor, int offset) {
        TopologyFieldItem entity = new TopologyFieldItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // backgroundURI
            cursor.getString(offset + 2), // title
            cursor.getString(offset + 3), // content
            cursor.getString(offset + 4) // imageURI
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TopologyFieldItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBackgroundURI(cursor.getString(offset + 1));
        entity.setTitle(cursor.getString(offset + 2));
        entity.setContent(cursor.getString(offset + 3));
        entity.setImageURI(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TopologyFieldItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TopologyFieldItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TopologyFieldItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
