com::angelmsger::cslaboratory::forum::topic::ForumTopicItem
Long com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.id
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.avatarURI
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.nickname
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.title
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.content
com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.ForumTopicItem()
com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.ForumTopicItem(Long id, String avatarURI, String nickname, String title, String content)
Long com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.bindValues, com.angelmsger.cslaboratory.dao.ForumTopicItemDao.getKey, com.angelmsger.cslaboratory.dao.ForumTopicItemDao.hasKey.
void com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.readEntity, com.angelmsger.cslaboratory.dao.ForumTopicItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.getAvatarURI()
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.bindValues, com.angelmsger.cslaboratory.forum.ForumRecyclerViewAdapter.ForumViewHolder.bind.
void com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.setAvatarURI(String avatarURI)
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.readEntity.
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.getNickname()
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.bindValues, com.angelmsger.cslaboratory.forum.ForumRecyclerViewAdapter.ForumViewHolder.bind.
void com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.setNickname(String nickname)
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.readEntity.
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.getTitle()
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.bindValues, com.angelmsger.cslaboratory.forum.ForumRecyclerViewAdapter.ForumViewHolder.bind.
void com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.readEntity.
String com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.getContent()
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.bindValues, com.angelmsger.cslaboratory.forum.ForumRecyclerViewAdapter.ForumViewHolder.bind.
void com.angelmsger.cslaboratory.forum.topic.ForumTopicItem.setContent(String content)
Referenced by com.angelmsger.cslaboratory.dao.ForumTopicItemDao.readEntity.