com::angelmsger::cslaboratory::topology::field::TopologyFieldItem
Long com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.id
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.backgroundURI
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.title
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.content
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.imageURI
com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.TopologyFieldItem()
com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.TopologyFieldItem(Long id, String backgroundURI, String title, String content, String imageURI)
Long com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.bindValues, com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.getKey, com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.hasKey.
void com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.readEntity, com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.getBackgroundURI()
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.bindValues, com.angelmsger.cslaboratory.topology.TopologyRecyclerViewAdapter.TopologyViewHolder.bind.
void com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.setBackgroundURI(String backgroundURI)
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.readEntity.
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.getTitle()
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.bindValues, com.angelmsger.cslaboratory.topology.TopologyRecyclerViewAdapter.TopologyViewHolder.bind.
void com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.readEntity.
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.getContent()
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.bindValues, com.angelmsger.cslaboratory.topology.TopologyRecyclerViewAdapter.TopologyViewHolder.bind.
void com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.setContent(String content)
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.readEntity.
String com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.getImageURI()
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.bindValues, com.angelmsger.cslaboratory.topology.TopologyRecyclerViewAdapter.TopologyViewHolder.bind.
void com.angelmsger.cslaboratory.topology.field.TopologyFieldItem.setImageURI(String imageURI)
Referenced by com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.readEntity.