com::angelmsger::cslaboratory::course::subclass::CourseCategoryItem
Long com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.id
String com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.title
List<CourseSubclassItem> com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.subclasses
com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.CourseCategoryItem()
com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.CourseCategoryItem(Long id, String title, List< CourseSubclassItem > subclasses)
com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.CourseCategoryItem(Long id, @NotNull String title)
Long com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.bindValues, com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.getKey, com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.hasKey.
void com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.readEntity, com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.getTitle()
Referenced by com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.ClassViewHolder.bind, com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.bindValues.
void com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.readEntity.
List<CourseSubclassItem> com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.getSubclasses()
Referenced by com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.ClassViewHolder.bind.
void com.angelmsger.cslaboratory.course.subclass.CourseCategoryItem.setSubclasses(List< CourseSubclassItem > subclasses)