com::angelmsger::cslaboratory::quality::category::QualityCategoryItem
Long com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.id
String com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.title
String com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.imageURI
com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.QualityCategoryItem()
com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.QualityCategoryItem(Long id, String title, String imageURI)
Long com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.bindValues, com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.getKey, com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.hasKey.
void com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.readEntity, com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.getTitle()
Referenced by com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.CategoryViewHolder.bind.
void com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.readEntity.
String com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.getImageURI()
Referenced by com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.CategoryViewHolder.bind.
void com.angelmsger.cslaboratory.quality.category.QualityCategoryItem.setImageURI(String imageURI)
Referenced by com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.readEntity.