com::angelmsger::cslaboratory::dao::DaoMaster
final int com.angelmsger.cslaboratory.dao.DaoMaster.SCHEMA_VERSION
static void com.angelmsger.cslaboratory.dao.DaoMaster.createAllTables(Database db, boolean ifNotExists)
Creates underlying database table using DAOs.
References com.angelmsger.cslaboratory.dao.CourseCourseItemDao.createTable, com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.createTable, com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.createTable, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.createTable, com.angelmsger.cslaboratory.dao.ForumTopicItemDao.createTable, com.angelmsger.cslaboratory.dao.QualityADItemDao.createTable, com.angelmsger.cslaboratory.dao.QualityArticleItemDao.createTable, com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.createTable, com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.createTable.
Referenced by com.angelmsger.cslaboratory.dao.DaoMaster.OpenHelper.onCreate.
static void com.angelmsger.cslaboratory.dao.DaoMaster.dropAllTables(Database db, boolean ifExists)
Drops underlying database table using DAOs.
References com.angelmsger.cslaboratory.dao.CourseCourseItemDao.dropTable, com.angelmsger.cslaboratory.dao.CourseCategoryItemDao.dropTable, com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.dropTable, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.dropTable, com.angelmsger.cslaboratory.dao.ForumTopicItemDao.dropTable, com.angelmsger.cslaboratory.dao.QualityADItemDao.dropTable, com.angelmsger.cslaboratory.dao.QualityArticleItemDao.dropTable, com.angelmsger.cslaboratory.dao.QualityCategoryItemDao.dropTable, com.angelmsger.cslaboratory.dao.TopologyFieldItemDao.dropTable.
Referenced by com.angelmsger.cslaboratory.dao.DaoMaster.DevOpenHelper.onUpgrade.
static DaoSession com.angelmsger.cslaboratory.dao.DaoMaster.newDevSession(Context context, String name)
WARNING: Drops all table on Upgrade! Use only during development. Convenience method using a DevOpenHelper.
References com.angelmsger.cslaboratory.dao.DaoMaster.DaoMaster, com.angelmsger.cslaboratory.dao.DaoMaster.newSession.
com.angelmsger.cslaboratory.dao.DaoMaster.DaoMaster(SQLiteDatabase db)
Referenced by com.angelmsger.cslaboratory.dao.DaoMaster.newDevSession.
com.angelmsger.cslaboratory.dao.DaoMaster.DaoMaster(Database db)
DaoSession com.angelmsger.cslaboratory.dao.DaoMaster.newSession()
Referenced by com.angelmsger.cslaboratory.CSLaboratory.onCreate, com.angelmsger.cslaboratory.dao.DaoMaster.newDevSession.
DaoSession com.angelmsger.cslaboratory.dao.DaoMaster.newSession(IdentityScopeType type)