com::angelmsger::cslaboratory::quality::QualityRecyclerViewAdapter
final List<QualityADItem> com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mQualityADItems
final List<QualityCategoryItem> com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mQualityCategoryItems
final List<QualityArticleItem> com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mQualityArticleItems
final int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mColCount
final LayoutInflater com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mInflater
final OnListFragmentInteractionListener com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mListener
final int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mCategoryItemsCount
Referenced by com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.onBindViewHolder.
final int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mPageCapacity
Referenced by com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.getItemViewType.
final int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mCategoryItemsRowCount
Referenced by com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityRecyclerViewAdapter, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.onBindViewHolder.
final int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mQualityItemsRowCount
Referenced by com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityRecyclerViewAdapter.
com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityRecyclerViewAdapter(List< QualityADItem > QualityADItems, List< QualityCategoryItem > qualityCategoryItems, List< QualityArticleItem > qualityArticleItems, final int colCount, LayoutInflater inflater, OnListFragmentInteractionListener listener)
References com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mCategoryItemsRowCount, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mQualityItemsRowCount.
int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.getItemViewType(int position)
References com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mPageCapacity.
Referenced by com.angelmsger.cslaboratory.quality.QualityFragment.onCreateView, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.onBindViewHolder.
ViewHolder com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.onCreateViewHolder(ViewGroup parent, int viewType)
void com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.onBindViewHolder(final ViewHolder holder, int position)
References com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.getItemViewType, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mCategoryItemsRowCount, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.mCategoryItemsCount.
int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.getItemCount()
int com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.getNextRequestOffset()
Referenced by com.angelmsger.cslaboratory.quality.QualityFragment.onCreateView.