com::angelmsger::cslaboratory::quality::ad::QualityADItem
Long com.angelmsger.cslaboratory.quality.ad.QualityADItem.id
String com.angelmsger.cslaboratory.quality.ad.QualityADItem.title
String com.angelmsger.cslaboratory.quality.ad.QualityADItem.imageURI
String com.angelmsger.cslaboratory.quality.ad.QualityADItem.actionURI
com.angelmsger.cslaboratory.quality.ad.QualityADItem.QualityADItem()
com.angelmsger.cslaboratory.quality.ad.QualityADItem.QualityADItem(Long id, String title, String imageURI, String actionURI)
Long com.angelmsger.cslaboratory.quality.ad.QualityADItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.bindValues, com.angelmsger.cslaboratory.dao.QualityADItemDao.getKey, com.angelmsger.cslaboratory.dao.QualityADItemDao.hasKey.
void com.angelmsger.cslaboratory.quality.ad.QualityADItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.readEntity, com.angelmsger.cslaboratory.dao.QualityADItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.quality.ad.QualityADItem.getTitle()
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.bindValues.
void com.angelmsger.cslaboratory.quality.ad.QualityADItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.readEntity.
String com.angelmsger.cslaboratory.quality.ad.QualityADItem.getImageURI()
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.bindValues.
void com.angelmsger.cslaboratory.quality.ad.QualityADItem.setImageURI(String imageURI)
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.readEntity.
String com.angelmsger.cslaboratory.quality.ad.QualityADItem.getActionURI()
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.bindValues.
void com.angelmsger.cslaboratory.quality.ad.QualityADItem.setActionURI(String actionURI)
Referenced by com.angelmsger.cslaboratory.dao.QualityADItemDao.readEntity.