com::angelmsger::cslaboratory::course::CourseRecyclerViewAdapter
final List<CourseCategoryItem> com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.mCourseCategoryItems
final List<CourseCourseItem> com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.mCourseCourseItems
final LayoutInflater com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.mInflater
Referenced by com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.ClassViewHolder.bind.
final OnListFragmentInteractionListener com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.mListener
Referenced by com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.ClassViewHolder.bind.
com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.CourseRecyclerViewAdapter(List< CourseCategoryItem > courseCourseCategoryItems, List< CourseCourseItem > courseCourseItems, LayoutInflater inflater, OnListFragmentInteractionListener listener)
int com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.getItemViewType(int position)
Referenced by com.angelmsger.cslaboratory.course.CourseFragment.onCreateView, com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.onBindViewHolder.
ViewHolder com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.onCreateViewHolder(ViewGroup parent, int viewType)
void com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.onBindViewHolder(final ViewHolder holder, int position)
References com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.getItemViewType.
int com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.getItemCount()
int com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.getNextRequestOffset()
Referenced by com.angelmsger.cslaboratory.course.CourseFragment.onCreateView.