com::angelmsger::cslaboratory::course::subclass::CourseSubclassItem
Long com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.id
String com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.imageURI
String com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.title
com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.CourseSubclassItem()
com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.CourseSubclassItem(Long id, String imageURI, String title)
Long com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.bindValues, com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.getKey, com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.hasKey.
void com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.readEntity, com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.getImageURI()
Referenced by com.angelmsger.cslaboratory.course.subclass.SubclassRecyclerViewAdapter.CourseClassViewHolder.bind, com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.bindValues.
void com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.setImageURI(String imageURI)
Referenced by com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.readEntity.
String com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.getTitle()
Referenced by com.angelmsger.cslaboratory.course.subclass.SubclassRecyclerViewAdapter.CourseClassViewHolder.bind, com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.bindValues.
void com.angelmsger.cslaboratory.course.subclass.CourseSubclassItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.CourseSubclassItemDao.readEntity.