com::angelmsger::cslaboratory::login::LoginActivity
CircularProgressButton com.angelmsger.cslaboratory.login.LoginActivity.mEmailSignInButton
Handler com.angelmsger.cslaboratory.login.LoginActivity.mHandler
Runnable com.angelmsger.cslaboratory.login.LoginActivity.mResetButton
Runnable com.angelmsger.cslaboratory.login.LoginActivity.mLoginSuccessfully
DataSource com.angelmsger.cslaboratory.login.LoginActivity.mDataSource
UserLoginTask com.angelmsger.cslaboratory.login.LoginActivity.mAuthTask
持续跟踪登录任务以保证当需要时可以取消。
AutoCompleteTextView com.angelmsger.cslaboratory.login.LoginActivity.mEmailView
Referenced by com.angelmsger.cslaboratory.login.LoginActivity.attemptLogin.
EditText com.angelmsger.cslaboratory.login.LoginActivity.mPasswordView
Referenced by com.angelmsger.cslaboratory.login.LoginActivity.attemptLogin.
final int com.angelmsger.cslaboratory.login.LoginActivity.LOGIN_SUCCESSFULLY
Referenced by com.angelmsger.cslaboratory.MainActivity.onActivityResult.
void com.angelmsger.cslaboratory.login.LoginActivity.onCreate(Bundle savedInstanceState)
References com.angelmsger.cslaboratory.login.LoginActivity.attemptLogin.
void com.angelmsger.cslaboratory.login.LoginActivity.attemptLogin()
来自登录表格的注册或登录请求。 如果存在非法输入 (无效的电子邮件地址，缺少填写的内容等。), 错误将被跳过并且不会发出登录请求。
References com.angelmsger.cslaboratory.login.LoginActivity.isPasswordValid, com.angelmsger.cslaboratory.login.LoginActivity.mPasswordView, com.angelmsger.cslaboratory.login.LoginActivity.mEmailView, com.angelmsger.cslaboratory.login.LoginActivity.isEmailValid.
Referenced by com.angelmsger.cslaboratory.login.LoginActivity.onCreate.
boolean com.angelmsger.cslaboratory.login.LoginActivity.isEmailValid(String email)
Referenced by com.angelmsger.cslaboratory.login.LoginActivity.attemptLogin.
boolean com.angelmsger.cslaboratory.login.LoginActivity.isPasswordValid(String password)
Referenced by com.angelmsger.cslaboratory.login.LoginActivity.attemptLogin.