com::angelmsger::cslaboratory::MainActivity
FloatingActionButton com.angelmsger.cslaboratory.MainActivity.mFloatingActionButton
ImageView com.angelmsger.cslaboratory.MainActivity.mDrawerImage
CircleImageView com.angelmsger.cslaboratory.MainActivity.mDrawerAvatar
TextView com.angelmsger.cslaboratory.MainActivity.mDrawerNickname
Button com.angelmsger.cslaboratory.MainActivity.mDrawerSigninButton
List<Fragment> com.angelmsger.cslaboratory.MainActivity.mFragments
List<NavigationTabBar.Model> com.angelmsger.cslaboratory.MainActivity.mModels
Referenced by com.angelmsger.cslaboratory.MainActivity.initUI, com.angelmsger.cslaboratory.MainActivity.onPageSelected, com.angelmsger.cslaboratory.MainActivity.onCourseListScroll, com.angelmsger.cslaboratory.MainActivity.onCourseListUpdate, com.angelmsger.cslaboratory.MainActivity.onDailyListScroll, com.angelmsger.cslaboratory.MainActivity.onDailyListUpdate, com.angelmsger.cslaboratory.MainActivity.onForumListScroll, com.angelmsger.cslaboratory.MainActivity.onForumListUpdate, com.angelmsger.cslaboratory.MainActivity.onQualityListScroll, com.angelmsger.cslaboratory.MainActivity.onQualityListUpdate, com.angelmsger.cslaboratory.MainActivity.onTopologyListScroll, com.angelmsger.cslaboratory.MainActivity.onTopologyListUpdate.
List<ColorStateList> com.angelmsger.cslaboratory.MainActivity.mColorStates
CSLaboratory com.angelmsger.cslaboratory.MainActivity.mApplication
final int com.angelmsger.cslaboratory.MainActivity.PERMISSIONS_REQUEST_INTERNET
final int com.angelmsger.cslaboratory.MainActivity.LOGIN_REQUEST
void com.angelmsger.cslaboratory.MainActivity.onCreate(Bundle savedInstanceState)
References com.angelmsger.cslaboratory.MainActivity.initUI, com.angelmsger.cslaboratory.MainActivity.requestPermission.
void com.angelmsger.cslaboratory.MainActivity.onActivityResult(int requestCode, int resultCode, Intent data)
References com.angelmsger.cslaboratory.login.LoginActivity.LOGIN_SUCCESSFULLY, com.angelmsger.cslaboratory.MainActivity.refreshUserinfo.
void com.angelmsger.cslaboratory.MainActivity.initUI()
References com.angelmsger.cslaboratory.daily.DailyFragment.newInstance, com.angelmsger.cslaboratory.forum.ForumFragment.newInstance, com.angelmsger.cslaboratory.quality.QualityFragment.newInstance, com.angelmsger.cslaboratory.course.CourseFragment.newInstance, com.angelmsger.cslaboratory.topology.TopologyFragment.newInstance, com.angelmsger.cslaboratory.MainActivity.mModels.
Referenced by com.angelmsger.cslaboratory.MainActivity.onCreate.
void com.angelmsger.cslaboratory.MainActivity.refreshUserinfo()
References com.angelmsger.cslaboratory.CSLaboratory.mGlobal, com.angelmsger.cslaboratory.login.User.getBase.
Referenced by com.angelmsger.cslaboratory.MainActivity.onActivityResult.
void com.angelmsger.cslaboratory.MainActivity.requestPermission()
Referenced by com.angelmsger.cslaboratory.MainActivity.onCreate.
void com.angelmsger.cslaboratory.MainActivity.onBackPressed()
boolean com.angelmsger.cslaboratory.MainActivity.onCreateOptionsMenu(Menu menu)
boolean com.angelmsger.cslaboratory.MainActivity.onOptionsItemSelected(MenuItem item)
boolean com.angelmsger.cslaboratory.MainActivity.onNavigationItemSelected(MenuItem item)
void com.angelmsger.cslaboratory.MainActivity.onPageScrolled(int position, float positionOffset, int positionOffsetPixels)
void com.angelmsger.cslaboratory.MainActivity.onPageSelected(int position)
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onPageScrollStateChanged(int state)
void com.angelmsger.cslaboratory.MainActivity.onCourseListScroll()
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onCourseListUpdate(final int updateCount)
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onCourseCategoryItemClick(CourseSubclassItem courseSubclassItem)
void com.angelmsger.cslaboratory.MainActivity.onCourseItemClick(CourseCourseItem courseCourseItem)
void com.angelmsger.cslaboratory.MainActivity.onDailyListScroll()
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onDailyListUpdate(int updateCount)
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onDailyItemClick(DailyArticleItem dailyArticleItem)
References com.angelmsger.cslaboratory.shared.ScrollingActivity.IMAGE_URI, com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getImageURI, com.angelmsger.cslaboratory.shared.ScrollingActivity.ARTICLE_TITLE, com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getTitle, com.angelmsger.cslaboratory.shared.ScrollingActivity.ARTICLE_CONTENT, com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getContent.
void com.angelmsger.cslaboratory.MainActivity.onForumListScroll()
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onForumListUpdate(int updateCount)
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onForumItemClick(ForumTopicItem forumTopicItem)
void com.angelmsger.cslaboratory.MainActivity.onQualityListScroll()
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onQualityListUpdate(int updateCount)
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onADItemClick(QualityADItem qualityAdItem)
void com.angelmsger.cslaboratory.MainActivity.onCategoryItemClick(QualityCategoryItem qualityCategoryItem)
void com.angelmsger.cslaboratory.MainActivity.onQualityItemClick(QualityArticleItem qualityArticleItem)
void com.angelmsger.cslaboratory.MainActivity.onTopologyListScroll()
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onTopologyListUpdate(int updateCount)
References com.angelmsger.cslaboratory.MainActivity.mModels.
void com.angelmsger.cslaboratory.MainActivity.onTopologyItemClick(TopologyFieldItem topologyFieldItem)