com::angelmsger::cslaboratory::daily::article::DailyArticleItem
Long com.angelmsger.cslaboratory.daily.article.DailyArticleItem.id
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.bannerURI
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.imageURI
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.title
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.content
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.postTime
com.angelmsger.cslaboratory.daily.article.DailyArticleItem.DailyArticleItem()
com.angelmsger.cslaboratory.daily.article.DailyArticleItem.DailyArticleItem(Long id, String bannerURI, String imageURI, String title, String content, String postTime)
Long com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.bindValues, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.getKey, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.hasKey.
void com.angelmsger.cslaboratory.daily.article.DailyArticleItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.readEntity, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getBannerURI()
Referenced by com.angelmsger.cslaboratory.daily.DailyRecyclerViewAdapter.DailyViewHolder.bind, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.bindValues.
void com.angelmsger.cslaboratory.daily.article.DailyArticleItem.setBannerURI(String bannerURI)
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getImageURI()
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.bindValues, com.angelmsger.cslaboratory.MainActivity.onDailyItemClick.
void com.angelmsger.cslaboratory.daily.article.DailyArticleItem.setImageURI(String imageURI)
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getTitle()
Referenced by com.angelmsger.cslaboratory.daily.DailyRecyclerViewAdapter.DailyViewHolder.bind, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.bindValues, com.angelmsger.cslaboratory.MainActivity.onDailyItemClick.
void com.angelmsger.cslaboratory.daily.article.DailyArticleItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getContent()
Referenced by com.angelmsger.cslaboratory.daily.DailyRecyclerViewAdapter.DailyViewHolder.bind, com.angelmsger.cslaboratory.dao.DailyArticleItemDao.bindValues, com.angelmsger.cslaboratory.MainActivity.onDailyItemClick.
void com.angelmsger.cslaboratory.daily.article.DailyArticleItem.setContent(String content)
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.daily.article.DailyArticleItem.getPostTime()
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.bindValues.
void com.angelmsger.cslaboratory.daily.article.DailyArticleItem.setPostTime(String postTime)
Referenced by com.angelmsger.cslaboratory.dao.DailyArticleItemDao.readEntity.