com::angelmsger::cslaboratory::shared::FullscreenActivity
final boolean com.angelmsger.cslaboratory.shared.FullscreenActivity.AUTO_HIDE
根据 AUTO_HIDE_DELAY_MILLIS 决定系统 UI 是否自动隐藏。
final int com.angelmsger.cslaboratory.shared.FullscreenActivity.AUTO_HIDE_DELAY_MILLIS
如果 AUTO_HIDE 被设置在隐藏系统 UI 前等待的毫秒数。
final int com.angelmsger.cslaboratory.shared.FullscreenActivity.UI_ANIMATION_DELAY
一些旧设备在 UI widget 更新与导航栏状态改变之间需要一小段延迟时间。
final Handler com.angelmsger.cslaboratory.shared.FullscreenActivity.mHideHandler
View com.angelmsger.cslaboratory.shared.FullscreenActivity.mContentView
final Runnable com.angelmsger.cslaboratory.shared.FullscreenActivity.mHidePart2Runnable
View com.angelmsger.cslaboratory.shared.FullscreenActivity.mControlsView
final Runnable com.angelmsger.cslaboratory.shared.FullscreenActivity.mShowPart2Runnable
boolean com.angelmsger.cslaboratory.shared.FullscreenActivity.mVisible
final Runnable com.angelmsger.cslaboratory.shared.FullscreenActivity.mHideRunnable
final View.OnTouchListener com.angelmsger.cslaboratory.shared.FullscreenActivity.mDelayHideTouchListener
用来为布局内部 UI 控制延迟隐藏系统 UI 的触摸事件监听器。 这将阻止在隐藏过程中对 activity UI 的操作。
Referenced by com.angelmsger.cslaboratory.shared.FullscreenActivity.onCreate.
void com.angelmsger.cslaboratory.shared.FullscreenActivity.onCreate(Bundle savedInstanceState)
References com.angelmsger.cslaboratory.shared.FullscreenActivity.toggle, com.angelmsger.cslaboratory.shared.FullscreenActivity.mDelayHideTouchListener.
void com.angelmsger.cslaboratory.shared.FullscreenActivity.onPostCreate(Bundle savedInstanceState)
References com.angelmsger.cslaboratory.shared.FullscreenActivity.delayedHide.
void com.angelmsger.cslaboratory.shared.FullscreenActivity.toggle()
References com.angelmsger.cslaboratory.shared.FullscreenActivity.hide, com.angelmsger.cslaboratory.shared.FullscreenActivity.show.
Referenced by com.angelmsger.cslaboratory.shared.FullscreenActivity.onCreate.
void com.angelmsger.cslaboratory.shared.FullscreenActivity.hide()
Referenced by com.angelmsger.cslaboratory.shared.FullscreenActivity.toggle.
void com.angelmsger.cslaboratory.shared.FullscreenActivity.show()
Referenced by com.angelmsger.cslaboratory.shared.FullscreenActivity.toggle.
void com.angelmsger.cslaboratory.shared.FullscreenActivity.delayedHide(int delayMillis)
计划一个在 [delay] 毫秒后对 hide() 的调用, 取消之前 已经计划的调用。
Referenced by com.angelmsger.cslaboratory.shared.FullscreenActivity.onPostCreate.