com::angelmsger::cslaboratory::login::BCrypt
final int com.angelmsger.cslaboratory.login.BCrypt.GENSALT_DEFAULT_LOG2_ROUNDS
final int com.angelmsger.cslaboratory.login.BCrypt.BCRYPT_SALT_LEN
Referenced by com.angelmsger.cslaboratory.login.BCrypt.gensalt.
final int com.angelmsger.cslaboratory.login.BCrypt.BLOWFISH_NUM_ROUNDS
final int com.angelmsger.cslaboratory.login.BCrypt.P_orig[][]
final int com.angelmsger.cslaboratory.login.BCrypt.S_orig[][]
final int com.angelmsger.cslaboratory.login.BCrypt.bf_crypt_ciphertext[][]
final char com.angelmsger.cslaboratory.login.BCrypt.base64_code[][]
final byte com.angelmsger.cslaboratory.login.BCrypt.index_64[][]
int com.angelmsger.cslaboratory.login.BCrypt.P[][]
int com.angelmsger.cslaboratory.login.BCrypt.S[][]
static String com.angelmsger.cslaboratory.login.BCrypt.encode_base64(byte d[], int len)
Encode a byte array using bcrypt's slightly-modified base64 encoding scheme. Note that this is not compatible with the standard MIME-base64 encoding. d the byte array to encode len the number of bytes to encode base64-encoded string IllegalArgumentException if the length is invalid
Referenced by com.angelmsger.cslaboratory.login.BCrypt.hashpw, com.angelmsger.cslaboratory.login.BCrypt.gensalt.
static byte com.angelmsger.cslaboratory.login.BCrypt.char64(char x)
Look up the 3 bits base64-encoded by the specified character, range-checking againt conversion table x the base64-encoded value the decoded value of x
Referenced by com.angelmsger.cslaboratory.login.BCrypt.decode_base64.
static byte [] com.angelmsger.cslaboratory.login.BCrypt.decode_base64(String s, int maxolen)
Decode a string encoded using bcrypt's base64 scheme to a byte array. Note that this is not compatible with the standard MIME-base64 encoding. s the string to decode maxolen the maximum number of bytes to decode an array containing the decoded bytes IllegalArgumentException if maxolen is invalid
References com.angelmsger.cslaboratory.login.BCrypt.char64.
Referenced by com.angelmsger.cslaboratory.login.BCrypt.hashpw.
static int com.angelmsger.cslaboratory.login.BCrypt.streamtoword(byte data[], int offp[])
Cycically extract a word of key material data the string to extract the data from offp a "pointer" (as a one-entry array) to the current offset into data the next word of material from data
Referenced by com.angelmsger.cslaboratory.login.BCrypt.key, com.angelmsger.cslaboratory.login.BCrypt.ekskey.
final void com.angelmsger.cslaboratory.login.BCrypt.encipher(int lr[], int off)
Blowfish encipher a single 64-bit block encoded as two 32-bit halves lr an array containing the two 32-bit half blocks off the position in the array of the blocks
Referenced by com.angelmsger.cslaboratory.login.BCrypt.key, com.angelmsger.cslaboratory.login.BCrypt.ekskey, com.angelmsger.cslaboratory.login.BCrypt.crypt_raw.
void com.angelmsger.cslaboratory.login.BCrypt.init_key()
Initialise the Blowfish key schedule
Referenced by com.angelmsger.cslaboratory.login.BCrypt.crypt_raw.
void com.angelmsger.cslaboratory.login.BCrypt.key(byte key[])
Key the Blowfish cipher key an array containing the key
References com.angelmsger.cslaboratory.login.BCrypt.streamtoword, com.angelmsger.cslaboratory.login.BCrypt.encipher.
Referenced by com.angelmsger.cslaboratory.login.BCrypt.crypt_raw.
void com.angelmsger.cslaboratory.login.BCrypt.ekskey(byte data[], byte key[])
Perform the "enhanced key schedule" step described by Provos and Mazieres in "A Future-Adaptable Password Scheme" http://www.openbsd.org/papers/bcrypt-paper.ps data salt information key password information
References com.angelmsger.cslaboratory.login.BCrypt.streamtoword, com.angelmsger.cslaboratory.login.BCrypt.encipher.
Referenced by com.angelmsger.cslaboratory.login.BCrypt.crypt_raw.
byte [] com.angelmsger.cslaboratory.login.BCrypt.crypt_raw(byte password[], byte salt[], int log_rounds)
Perform the central password hashing step in the bcrypt scheme password the password to hash salt the binary salt to hash with the password log_rounds the binary logarithm of the number of rounds of hashing to apply an array containing the binary hashed password
References com.angelmsger.cslaboratory.login.BCrypt.init_key, com.angelmsger.cslaboratory.login.BCrypt.ekskey, com.angelmsger.cslaboratory.login.BCrypt.key, com.angelmsger.cslaboratory.login.BCrypt.encipher.
Referenced by com.angelmsger.cslaboratory.login.BCrypt.hashpw.
static String com.angelmsger.cslaboratory.login.BCrypt.hashpw(String password, String salt)
Hash a password using the OpenBSD bcrypt scheme password the password to hash salt the salt to hash with (perhaps generated using BCrypt.gensalt) the hashed password
References com.angelmsger.cslaboratory.login.BCrypt.decode_base64, com.angelmsger.cslaboratory.login.BCrypt.crypt_raw, com.angelmsger.cslaboratory.login.BCrypt.encode_base64.
Referenced by com.angelmsger.cslaboratory.login.BCrypt.checkpw.
static String com.angelmsger.cslaboratory.login.BCrypt.gensalt(int log_rounds, SecureRandom random)
Generate a salt for use with the BCrypt.hashpw() method log_rounds the log2 of the number of rounds of hashing to apply - the work factor therefore increases as 2**log_rounds. random an instance of SecureRandom to use an encoded salt value
References com.angelmsger.cslaboratory.login.BCrypt.BCRYPT_SALT_LEN, com.angelmsger.cslaboratory.login.BCrypt.encode_base64.
static String com.angelmsger.cslaboratory.login.BCrypt.gensalt(int log_rounds)
Generate a salt for use with the BCrypt.hashpw() method log_rounds the log2 of the number of rounds of hashing to apply - the work factor therefore increases as 2**log_rounds. an encoded salt value
References com.angelmsger.cslaboratory.login.BCrypt.gensalt.
static String com.angelmsger.cslaboratory.login.BCrypt.gensalt()
Generate a salt for use with the BCrypt.hashpw() method, selecting a reasonable default for the number of hashing rounds to apply an encoded salt value
Referenced by com.angelmsger.cslaboratory.login.BCrypt.gensalt.
static boolean com.angelmsger.cslaboratory.login.BCrypt.checkpw(String plaintext, String hashed)
Check that a plaintext password matches a previously hashed one plaintext the plaintext password to verify hashed the previously-hashed password true if the passwords match, false otherwise
References com.angelmsger.cslaboratory.login.BCrypt.hashpw.
Referenced by com.angelmsger.cslaboratory.login.PHPass.CheckPassword.