com::angelmsger::cslaboratory::course::course::CourseCourseItem
Long com.angelmsger.cslaboratory.course.course.CourseCourseItem.id
String com.angelmsger.cslaboratory.course.course.CourseCourseItem.imageURI
String com.angelmsger.cslaboratory.course.course.CourseCourseItem.title
String com.angelmsger.cslaboratory.course.course.CourseCourseItem.actionURI
int com.angelmsger.cslaboratory.course.course.CourseCourseItem.learnNum
com.angelmsger.cslaboratory.course.course.CourseCourseItem.CourseCourseItem()
com.angelmsger.cslaboratory.course.course.CourseCourseItem.CourseCourseItem(Long id, String imageURI, String title, String actionURI, int learnNum)
Long com.angelmsger.cslaboratory.course.course.CourseCourseItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.CourseCourseItemDao.bindValues, com.angelmsger.cslaboratory.dao.CourseCourseItemDao.getKey, com.angelmsger.cslaboratory.dao.CourseCourseItemDao.hasKey.
void com.angelmsger.cslaboratory.course.course.CourseCourseItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.CourseCourseItemDao.readEntity, com.angelmsger.cslaboratory.dao.CourseCourseItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.course.course.CourseCourseItem.getImageURI()
Referenced by com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.CourseViewHolder.bind, com.angelmsger.cslaboratory.dao.CourseCourseItemDao.bindValues.
void com.angelmsger.cslaboratory.course.course.CourseCourseItem.setImageURI(String imageURI)
Referenced by com.angelmsger.cslaboratory.dao.CourseCourseItemDao.readEntity.
String com.angelmsger.cslaboratory.course.course.CourseCourseItem.getTitle()
Referenced by com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.CourseViewHolder.bind, com.angelmsger.cslaboratory.dao.CourseCourseItemDao.bindValues.
void com.angelmsger.cslaboratory.course.course.CourseCourseItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.CourseCourseItemDao.readEntity.
String com.angelmsger.cslaboratory.course.course.CourseCourseItem.getActionURI()
Referenced by com.angelmsger.cslaboratory.dao.CourseCourseItemDao.bindValues.
void com.angelmsger.cslaboratory.course.course.CourseCourseItem.setActionURI(String actionURI)
Referenced by com.angelmsger.cslaboratory.dao.CourseCourseItemDao.readEntity.
int com.angelmsger.cslaboratory.course.course.CourseCourseItem.getLearnNum()
Referenced by com.angelmsger.cslaboratory.course.CourseRecyclerViewAdapter.CourseViewHolder.bind, com.angelmsger.cslaboratory.dao.CourseCourseItemDao.bindValues.
void com.angelmsger.cslaboratory.course.course.CourseCourseItem.setLearnNum(int learnNum)
Referenced by com.angelmsger.cslaboratory.dao.CourseCourseItemDao.readEntity.