com::angelmsger::cslaboratory::quality::article::QualityArticleItem
Long com.angelmsger.cslaboratory.quality.article.QualityArticleItem.id
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.title
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.group
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.content
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.imageURI
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.actionURI
int com.angelmsger.cslaboratory.quality.article.QualityArticleItem.bangCount
int com.angelmsger.cslaboratory.quality.article.QualityArticleItem.commentCount
com.angelmsger.cslaboratory.quality.article.QualityArticleItem.QualityArticleItem()
com.angelmsger.cslaboratory.quality.article.QualityArticleItem.QualityArticleItem(Long id, String title, String group, String content, String imageURI, String actionURI, int bangCount, int commentCount)
Long com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getId()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues, com.angelmsger.cslaboratory.dao.QualityArticleItemDao.getKey, com.angelmsger.cslaboratory.dao.QualityArticleItemDao.hasKey.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setId(Long id)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity, com.angelmsger.cslaboratory.dao.QualityArticleItemDao.updateKeyAfterInsert.
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getTitle()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder.bind.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setTitle(String title)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getGroup()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder.bind.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setGroup(String group)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getContent()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder.bind.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setContent(String content)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getImageURI()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder.bind.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setImageURI(String imageURI)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity.
String com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getActionURI()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setActionURI(String actionURI)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity.
int com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getBangCount()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder.bind.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setBangCount(int bangCount)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity.
int com.angelmsger.cslaboratory.quality.article.QualityArticleItem.getCommentCount()
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.bindValues, com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder.bind.
void com.angelmsger.cslaboratory.quality.article.QualityArticleItem.setCommentCount(int commentCount)
Referenced by com.angelmsger.cslaboratory.dao.QualityArticleItemDao.readEntity.