com::angelmsger::cslaboratory::daily::DailyFragment::OnListFragmentInteractionListener
void com.angelmsger.cslaboratory.daily.DailyFragment.OnListFragmentInteractionListener.onDailyListScroll()
Referenced by com.angelmsger.cslaboratory.daily.DailyFragment.onCreateView.
void com.angelmsger.cslaboratory.daily.DailyFragment.OnListFragmentInteractionListener.onDailyListUpdate(final int updateCount)
Referenced by com.angelmsger.cslaboratory.daily.DailyFragment.AsynLoadData.onPostExecute.
void com.angelmsger.cslaboratory.daily.DailyFragment.OnListFragmentInteractionListener.onDailyItemClick(DailyArticleItem dailyArticleItem)
Referenced by com.angelmsger.cslaboratory.daily.DailyRecyclerViewAdapter.DailyViewHolder.bind.