com::angelmsger::cslaboratory::source::DataSource
Login.Response com.angelmsger.cslaboratory.source.DataSource.attemptLogin(Login.Request request)
Referenced by com.angelmsger.cslaboratory.login.LoginActivity.UserLoginTask.doInBackground.
CourseContent com.angelmsger.cslaboratory.source.DataSource.getCourseContent(final int offset, final int limit)
DailyContent com.angelmsger.cslaboratory.source.DataSource.getDailyContent(final int offset, final int limit)
ForumContent com.angelmsger.cslaboratory.source.DataSource.getForumContent(final int offset, final int limit)
Referenced by com.angelmsger.cslaboratory.forum.ForumFragment.ForumFragment.
QualityContent com.angelmsger.cslaboratory.source.DataSource.getQualityContent(final int offset, final int limit)
Referenced by com.angelmsger.cslaboratory.quality.QualityFragment.QualityFragment.
TopologyContent com.angelmsger.cslaboratory.source.DataSource.getTopologyContent(final int offset, final int limit)
Referenced by com.angelmsger.cslaboratory.topology.TopologyFragment.TopologyFragment.