com::angelmsger::cslaboratory::quality::QualityFragment::OnListFragmentInteractionListener
void com.angelmsger.cslaboratory.quality.QualityFragment.OnListFragmentInteractionListener.onQualityListScroll()
Referenced by com.angelmsger.cslaboratory.quality.QualityFragment.onCreateView.
void com.angelmsger.cslaboratory.quality.QualityFragment.OnListFragmentInteractionListener.onQualityListUpdate(final int updateCount)
Referenced by com.angelmsger.cslaboratory.quality.QualityFragment.AsynLoadData.onPostExecute.
void com.angelmsger.cslaboratory.quality.QualityFragment.OnListFragmentInteractionListener.onADItemClick(QualityADItem qualityAdItem)
Referenced by com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.ADPagerAdapter.ADPagerAdapter.
void com.angelmsger.cslaboratory.quality.QualityFragment.OnListFragmentInteractionListener.onCategoryItemClick(QualityCategoryItem qualityCategoryItem)
Referenced by com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.CategoryViewHolder.bind.
void com.angelmsger.cslaboratory.quality.QualityFragment.OnListFragmentInteractionListener.onQualityItemClick(QualityArticleItem qualityArticleItem)
Referenced by com.angelmsger.cslaboratory.quality.QualityRecyclerViewAdapter.QualityViewHolder.bind.